### ISSUE TITLE
Cant Open my first Manim Project

### ISSUE THREAD

**Issue by Shantanu-Manim** [ManimCommunity/manim#1055] opened 2021-02-25 17:26 UTC
Cant Open my first Manim Project
i have coded
![hello](https://user-images.githubusercontent.com/79604276/109191448-31eb6700-77bc-11eb-85f1-471446813f26.png)
then runned in cmd and then error popped up
ImportError: DLL load failed while importing cv2: The specified module could not be found
![cmd](https://user-images.githubusercontent.com/79604276/109191504-40d21980-77bc-11eb-8e4f-6c774a7cbeb0.png)
I have a good idea of Python but new to Manim
downloaded Manim Folder from here only 
also runned command on cmd pip install manim and output was all requirements satisfied

**Comment by kilacoda** [comment] 2021-02-25 18:15
Change the import to `from manim import *`. `manimlib` likely points to an old version of 3b1b/manim on your system.

**Comment by Shantanu-Manim** [comment] 2021-02-25 18:17
You mean that I should write that thing in the the first line of my
hello.py ??

**Comment by kilacoda** [comment] 2021-02-25 18:19
Yes.
`from manimlib.imports import *` -> `from manim import *`

**Comment by Shantanu-Manim** [comment] 2021-02-25 18:44
i have done this but its now showing these error
![warning](https://user-images.githubusercontent.com/79604276/109200755-fefaa080-77c6-11eb-99b1-2bd8039486c6.png)
after that this package installation dialog box
![pkg_install](https://user-images.githubusercontent.com/79604276/109201132-7a5c5200-77c7-11eb-8c72-b9995394d883.png)
and after clicking install these bunch of errors
![error](https://user-images.githubusercontent.com/79604276/109201210-92cc6c80-77c7-11eb-9bbf-5add8ec63bb5.png)
![latw_error](https://user-images.githubusercontent.com/79604276/109201218-94963000-77c7-11eb-8dcc-371d9c692de3.png)

**Comment by Darylgolden** [comment] 2021-02-26 01:04
Try changing `TextMobject` to `Text`

**Comment by Darylgolden** [comment] 2021-02-26 01:05
In future, it may be faster and more convenient to get help from the discord server.

**Comment by Shantanu-Manim** [comment] 2021-02-26 06:28
tHANK you VERY VERY much. could you tell why previously it wasn't working and does it mean i should use Text always.
and now its working but still one error is coming whats the issue with it.
(process:1904): GLib-GIO-WARNING **: 11:54:01.043: Unexpectedly, UWP app `20815shootingapp.AirFileViewer_1.4.10.0_x64__xcg28tkrsnqww' (AUMId `20815shootingapp.AirFileViewer_xcg28tkrsnqww!App') supports 316 extensions but has no verbs
![hello](https://user-images.githubusercontent.com/79604276/109263701-bd4f1180-7829-11eb-8d99-df964546a4e8.png)
and from where should i learn Manim which i have downloaded from here
please help me to sort out these problem for one time last please

**Comment by Shantanu-Manim** [comment] 2021-02-26 06:58
and where is the discord server ???

**Comment by Shantanu-Manim** [comment] 2021-02-26 07:12
please help me

**Comment by kilacoda** [comment] 2021-02-26 07:27
Your error seems to not be caused by manim but something on your system, so we won't be able to help you with that, sorry. Though it doesn't look like it messes up rendering anyhow so I think you could just ignore it for now.

See the README for this repository (on the [front page](https://github.com/manimcommunity/manim)) for the discord link. Putting it here anyways though: https://discord.gg/mMRrZQW

> why i have to change the import statement from manimlib.imports import * -> from manim import *

Primarily because we changed it, since it looks better and is more pythonic. `manimlib.imports` is what you import from in the [3b1b version](https://github.com/3b1b/manim).

**Comment by kilacoda** [comment] 2021-02-26 07:32
Closing, since I assume all issues have been resolved.

**Closed by kilacoda** 2021-02-26 07:32 UTC

**Comment by Shantanu-Manim** [comment] 2021-02-26 07:38
> Closing, since I assume all issues have been resolved.

YUP ALL ISSUE HAVE BEEN SORT OUT
