### ISSUE TITLE
There are no scenes inside that module

### ISSUE THREAD

**Issue by nilanc** [ManimCommunity/manim#2045] opened 2021-09-14 07:09 UTC
#### Preliminaries

- [ ] I have followed the latest version of the
      [installation instructions](https://docs.manim.community/en/stable/installation.html).
- [ ] I have checked the [troubleshooting page](https://docs.manim.community/en/stable/installation/troubleshooting.html) and my problem is either not mentioned there,
      or the solution given there does not help.

## Description of error

I have followed the latest installation manual and have used 'choco install manimce' to install on Windows10.
The first example in the 'https://docs.manim.community/en/stable/tutorials/quickstart.html' works perfectly,
but the when I try the second examle in the same page it gives me below error.
D:\My\manimProjects>manim -pql Test1.py  quareToCircle
Manim Community v0.10.0
[09/14/21 16:52:35] ERROR                                                                                                                                                                                       module_ops.py:73
There are no scenes inside that module

## Installation logs

<details><summary>Terminal output</summary>

```
D:\My\manimProjects>manim -pql Test1.py  quareToCircle
Manim Community v0.10.0

[09/14/21 16:12:32] ERROR                                                                              module_ops.py:73
                                There are no scenes inside that module
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS : Windows 10 
- RAM: 16GB
- Python version (`python/py/python3 --version`): Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38)
- Installed modules (provide output from `pip list`):
```
D:\My\manimProjects>pip list
Package             Version
------------------- ---------
certifi             2021.5.30
charset-normalizer  2.0.4
click               8.0.1
click-default-group 1.2.2
cloup               0.7.1
colorama            0.4.4
colour              0.1.5
commonmark          0.9.1
decorator           5.1.0
glcontext           2.3.4
idna                3.2
manim               0.10.0
ManimPango          0.3.0
mapbox-earcut       0.12.10
moderngl            5.6.4
moderngl-window     2.4.0
multipledispatch    0.6.0
networkx            2.6.3
numpy               1.21.2
Pillow              8.3.2
pip                 21.2.4
pycairo             1.20.1
pydub               0.25.1
pyglet              1.5.20
Pygments            2.10.0
pyrr                0.10.3
requests            2.26.0
rich                10.9.0
scipy               1.7.1
screeninfo          0.6.7
setuptools          58.0.4
six                 1.16.0
tqdm                4.62.2
urllib3             1.26.6
watchdog            2.1.5
wheel               0.37.0
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020): No
+ Installed LaTeX packages: No

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`: 

```
D:\My\manimProjects>ffmpeg -version
ffmpeg version 4.4-essentials_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100
```
</details>

**Comment by Darylgolden** [comment] 2021-09-14 07:21
`SquareToCircle`, not `quareToCircle`.

**Comment by kilacoda** [comment] 2021-09-18 21:16
Closing, since this seems to be a caused by a simple typo.

**Closed by kilacoda** 2021-09-18 21:16 UTC
Labels: installation
