### ISSUE TITLE
Transparent background -t doesn't work

### ISSUE THREAD

**Issue by FilipeMarch** [ManimCommunity/manim#473] opened 2020-09-24 14:15 UTC
I was used to do something like:
```python
class Alphabet(Scene):
    def construct(self):
        alpha = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
        for letter in alpha:
            text = TextMobject(letter).set_height(7.5).set_color(BLACK)
            self.add(text)
            self.wait(0.1)
            self.remove(text)
```
```shell
python -m manim script3.py Alphabet -pt
``` 
Getting this:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/23220309/94156693-becd7580-fe56-11ea-92b9-17f4c00a18ac.gif)

Using the same script and shell command with ManimCE produces this:
![image](https://user-images.githubusercontent.com/23220309/94156945-081dc500-fe57-11ea-8062-5b590eedfd59.png)

**Comment by huguesdevimeux** [comment] 2020-10-03 12:14
Thanks for the report. 
This is probably due to this line that is not present in manim ce : 

https://github.com/3b1b/manim/blob/19e3c97589181ffd43ef14d9169af4e40e054664/manimlib/config.py#L162

This should probably be an easy fix, realted to config. Cc @leotrs

**Comment by kolibril13** [comment] 2020-10-14 19:11
I just had a look on it.
If I run manim with -t,

I can have a look at 
```
class ABC(Scene):
    def construct(self):
        dot = Dot().set_color(GREEN)
        self.add(dot)
        self.wait(1)
        print(*file_writer_config.items() , sep = "\n")
```
that tells me
```
('png_mode', 'RGBA')
('movie_file_extension', '.mov')
```
So in principle, that is what we want to have.
Also, with the -t tag, manim goes to the scene_file_writer.py into the if statement:
```
        if file_writer_config["movie_file_extension"] == ".mov":
            # This is if the background of the exported
            # video should be transparent.
            command += [
                "-vcodec",
                "qtrle",
            ]
```
So it even uses the codec for transparency.
As I have some time tomorrow, can you tell me where I have to look and make changes? :)

**Comment by leotrs** [comment] 2020-10-15 22:29
I'm not sure where to make the changes, but if you end up working on that please make sure to add a test for this so there are no regressions.

**Comment by leotrs** [comment] 2020-10-28 20:12
Note to self: this will be fixed by #620

**Comment by leotrs** [comment] 2020-10-29 20:01
@FilipeMarch would you please kindly pull the latest master branch and try again? I believe this should be fixed now :)

**Comment by leotrs** [comment] 2020-10-31 01:45
@kolibril13 has confirmed that the -t flag now works.

**Closed by leotrs** 2020-10-31 01:45 UTC
Labels: bug
