### ISSUE TITLE
Update attributes fails through self.play with setters

### ISSUE THREAD

**Issue by ponmike92** [ManimCommunity/manim#664] opened 2020-11-01 20:46 UTC
All attributes of child classes from VMobject are not updating if we use "setter" methods in self.play. Even if we declare them through CONFIG dictionary. Code beneath shows this problem.

Surprisingly, I first thought that it is normal behaviour. But it is not the same if we try to set base VMobject attributes like stroke_width.
I suppose it is known issue because I found mention in source code in Line class. 

What do you think? Is it something wrong in parser which handles methods placed in self.play?

```python
from manim import *

class UpdateAttributesFail(Scene):
    def construct(self):
        
        line = Line(LEFT, RIGHT)

        print("stroke before: ", line.stroke_width)
        print("start before: ", line.start)
        print("end before: ", line.end)

        self.play(
            line.put_start_and_end_on, UP, DOWN,
            line.set_stroke, None, 10, None,
        )

        print("stroke after: ", line.stroke_width)
        print("start after: ", line.start)
        print("end after: ", line.end)
```

```
stroke before:  4
start before:  [-1.  0.  0.]
end before:  [1. 0. 0.]

stroke after:  10                                                                                                                                
start after:  [-1.  0.  0.]
end after:  [1. 0. 0.]
```

**Comment by leotrs** [comment] 2020-11-01 21:45
Thanks for reporting. This is essentially a duplicate of #258 

We have not gotten around to fixing this yet because fixing it effectively once and for all requires a more robust test suite than what we have now.

**Comment by huguesdevimeux** [comment] 2020-11-01 22:01
It's also and mostly due to all the `CONFIG` system. The only times attributes like these are touched is during the instantanciation if the `Mobject`, when all the thing contained in CONFIG are merged with the parameters passed in the decleration. 

This will likely be fixed when we'll finally get rid of CONFIG, but it's still a good thing to have it fixed. 

On a side note, I think we should replace #258 with this issue, as the first is, well, pretty dead non :/

**Comment by ponmike92** [comment] 2020-11-02 06:38
For me idea of CONFIG is convenient. It can shorten your code with creating class attributes. Am I right that you are trying to achieve something like this?

Old style:
```
python
class MyVMObject(VMobject):
    CONFIG = {"value": 1, "text": "my text"}

    def __init__(self, **kwargs):
        VMobject.__init__(self, **kwargs)
```

New style:
```
python
class MyVMObject(VMobject):
    DEFAULT_VALUE = 1
    DEFAULT_TEXT = "my text"

    def __init__(self, **kwargs):
        VMobject.__init__(self)

        self.value = kwargs["value"] if "value" in kwargs else self.DEFAULT_VALUE
        self.text = kwargs["text"] if "text" in kwargs else self.DEFAULT_TEXT
```

**Comment by ponmike92** [comment] 2020-11-02 07:18
I think that it can be a good idea to leave CONFIG  for child classes:
+ you don't break users code
+ you still have ability to create class attributes easily (with digest_config method)

BUT cut it off for all bases classes like VMobject and Mobject:
+ clear code, easy for debugging

**Comment by leotrs** [comment] 2020-11-02 12:36
> It is sad that it is not easy to fix issue.

Agreed.

> For me idea of CONFIG is elegant. It can shorten your code without creating class attributes yourself. 

It is a solution that allows for less boilerplate code. But it is extremely difficult to debug, document, maintain, and improve. It is not pythonic, it is basically trying to patch how inheritance works.

> Am I right that you are trying to achieve something like that?
> ```python
> class MyObj(Mobject):
>     DEFAULT_VALUE = 1
>     DEFAULT_TEXT = "my text"
> 
>     def __init__(self, **kwargs):
>         Mobject.__init__(self)
> 
>         self.value = kwargs["value"] if "value" in kwargs else self.DEFAULT_VALUE
>         self.text = kwargs["text"] if "text" in kwargs else self.DEFAULT_TEXT
> ```

No. I would personally like to write something like this
> ```python
> class MyObj(Mobject):
>     def __init__(self, value=1, text="my text"):
>         Mobject.__init__(self)
>         self.value = value
>         self.text = text
> ```
Note `value` and `text` do not need to be passed to Mobject.

> But what if we have 20 attributes?

You write 20 lines of the above.

> All of them will be created in the same way.

Yes. Why is this a problem? They are simple lines, easy to debug, document, maintain, and improve.

> What is better replacement for this implementation?

We have discussed using either dataclasses of attrs in the past, but recently there's been talk of moving to standard classes first before deciding if we want to commit to some other library like that.

> you don't break users code

The whole point of NOT fixing this UNTIL we have enough tests is so that we can fix this without breaking user code.

> you still have ability to create class attributes easily (with digest_config method)

I don't understand why doing this is not considered easy:
```python
class MyObj(Mobject):
    def __init__(self, value=1, text="my text"):
        Mobject.__init__(self)
        self.value = value
        self.text = text
```

> BUT cut it off for all bases classes like VMobject and Mobject: clear code, easy for debugging

Cutting it from certain classes before cutting it from others is a smart way to go about it. Feel free to submit a PR.

**Comment by ponmike92** [comment] 2020-11-02 13:40
@leotrs, thank you for deployed answer! Im not strong in class architectures but now it is clear for me. Sorry if ask stupid question ;)

I'm not strong with git but hope to help you in development in future. Have to understand how manim organized deeper first.

**Comment by leotrs** [comment] 2020-11-02 14:20
Not a stupid question at all!

We look forward to seeing your contributions.

**Comment by behackl** [comment] 2020-11-16 02:47
Closing this, as this is a duplicate.

**Closed by behackl** 2020-11-16 02:47 UTC
Labels: duplicate/wontfix
