### ISSUE TITLE
Transparent background -t currently not working?

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#545] opened 2020-10-14 12:59 UTC
When I have this script:

```python
from manim import *

class Test(GraphScene):
    def construct(self):
        self.add(Circle(fill_opacity = 0.3))


import os
from pathlib import Path
if __name__ == "__main__":
    script_name = f"{Path(__file__).resolve()}"
    os.system(f"manim   -t   --disable_caching -s -p  " + script_name)
```
I get this output, which has a black background, instead of a transparent one:
![Test](https://user-images.githubusercontent.com/44469195/95991935-aafda980-0e2d-11eb-8941-b32b7a892115.png)
Does that mean that the -t flag is currently broken?
Or did I make a mistake?

**Comment by leotrs** [comment] 2020-10-14 13:02
Closing as duplicate of #473

**Closed by leotrs** 2020-10-14 13:02 UTC
Labels: bug
