### ISSUE TITLE
I want to know there is a threeD table in Mainm?

### ISSUE THREAD

**Issue by LingfuD** [ManimCommunity/manim#3757] opened 2024-05-14 01:55 UTC
I want to make a video about three dimension  DP problem. So I'm finding the three dimension table. So is the feature in Mainm? please.

**Comment by uwezi** [comment] 2024-05-14 07:45
duplicate of https://github.com/ManimCommunity/manim/discussions/3758

**Comment by JasonGrace2282** [comment] 2024-05-21 03:03
Duplicate

**Closed by JasonGrace2282** 2024-05-21 03:03 UTC
Labels: new feature
