### ISSUE TITLE
Problem with updating the angle measure 

### ISSUE THREAD

**Issue by Musimatician** [ManimCommunity/manim#3698] opened 2024-04-13 08:07 UTC
Hello, here is a code I wrote, my intention is to make a point move on a circle and the display the measure of a certain angle.
But, the measure displayed on the screen would never change, would never get updated.
Would anyone help me find the problem ?
Thans in advance

class geometry (Scene) :
    def construct (self) :
        angleAOM = ValueTracker(20)
        circle = Circle().scale(3)
        circle.set(color=RED, stroke_width=6)
        O = Dot(circle.get_center())
        A = Dot(circle.point_at_angle(0*DEGREES))
        B = Dot(circle.point_at_angle(180*DEGREES))
        M = always_redraw(lambda: Dot(circle.point_at_angle(angleAOM.get_value()*DEGREES), color=BLUE))
        AB = Line(A.get_center(), B.get_center()).set_color(PURE_BLUE)
        BA = Line(B.get_center(), A.get_center()).set_color(PURE_BLUE)
        AM = always_redraw(lambda: Line(A.get_center(), M.get_center(), color=GREEN, stroke_width=5))
        MA = always_redraw(lambda: Line(M.get_center(), A.get_center(), color=GREEN, stroke_width=5))
        MB = always_redraw(lambda: Line(M.get_center(), B.get_center(), color=YELLOW, stroke_width=5))
        BM = always_redraw(lambda: Line(B.get_center(), M.get_center(), color=YELLOW, stroke_width=5))
        PointO = Text("O", weight=BOLD, color=GOLD).next_to(O, DOWN).scale(0.5).shift(0.2*UP)
        PointA = Text("A", weight=BOLD, color=GOLD).next_to(A, RIGHT).scale(0.5).shift(0.2*LEFT)
        PointB = Text("B", weight=BOLD, color=GOLD).next_to(B, LEFT).scale(0.5).shift(0.2*RIGHT)
        PointM = always_redraw(lambda: Text("M", weight=BOLD, color=BLUE).next_to(M, UP).scale(0.5).shift(0.2*DOWN))
        self.play(Create(circle), run_time=2)
        AngleMAB = always_redraw(lambda: Angle(AM, AB, quadrant=(1,1), color=BLUE, radius=0.5, stroke_width=5))
        valueofAngleMAB = always_redraw(lambda: DecimalNumber(AngleMAB.get_value(degrees=True), unit="^{\circ}"))
        AngleAMB = always_redraw(lambda: RightAngle(MB, AM, quadrant=(1,-1), color=BLUE, length=0.4, stroke_width=5))
        arcofangleMBA = Angle(BA, BM, quadrant=(1,1), color=DARK_BROWN, radius=0.75, stroke_width=5)
        self.play(FadeIn(O, A, B, M, PointO, PointA, PointB, PointM, AB, AM, MB, AngleMAB, AngleAMB, arcofangleMBA,
                         valueofAngleMAB), run_time=3)
        self.wait(0)
        self.play(angleAOM.animate.set_value(179), rate_func=linear, run_time=10)
        self.wait()

**Comment by uwezi** [comment] 2024-04-13 09:44
If you include code you need to properly format it in Markup editors like here on github or on Discord - where I would like to point you for better help and better discussions.

Your question is not an issue with the code base of Manim - it is caused by a misunderstanding on how Manim works and we gladly help you to learn more about Manim here: [Where can I find more resources for learning Manim?](https://docs.manim.community/en/stable/faq/general.html?highlight=discord#where-can-i-find-more-resources-for-learning-manim)

Your lines BA and BM are never added to the scene, therefore especially the updater of the line BM is never executed.

I am not sure why the `always_redraw` on your `DecimalNumber()` does not work, but here is a working version of your code:

```py
class geometry (Scene) :
    def construct (self) :
        angleAOM = ValueTracker(20)
        circle = Circle().scale(3)
        circle.set(color=RED, stroke_width=6)
        O = Dot(circle.get_center())
        A = Dot(circle.point_at_angle(0*DEGREES))
        B = Dot(circle.point_at_angle(180*DEGREES))
        M = always_redraw(lambda:
            Dot(circle.point_at_angle(angleAOM.get_value()*DEGREES), color=BLUE)
        )
        AB = Line(A.get_center(), B.get_center()).set_color(PURE_BLUE)
        BA = Line(B.get_center(), A.get_center()).set_color(PURE_BLUE)
        AM = always_redraw(lambda:
            Line(A.get_center(), M.get_center(), color=GREEN, stroke_width=5)
        )
        MA = always_redraw(lambda:
            Line(M.get_center(), A.get_center(), color=GREEN, stroke_width=5)
        )
        MB = always_redraw(lambda:
            Line(M.get_center(), B.get_center(), color=YELLOW, stroke_width=5)
        )
        BM = always_redraw(lambda:
            Line(B.get_center(), M.get_center(), color=YELLOW, stroke_width=5)
        )
        PointO = Text("O", weight=BOLD, color=GOLD).next_to(O, DOWN).scale(0.5).shift(0.2*UP)
        PointA = Text("A", weight=BOLD, color=GOLD).next_to(A, RIGHT).scale(0.5).shift(0.2*LEFT)
        PointB = Text("B", weight=BOLD, color=GOLD).next_to(B, LEFT).scale(0.5).shift(0.2*RIGHT)
        PointM = always_redraw(lambda: Text("M", weight=BOLD, color=BLUE).next_to(M, UP).scale(0.5).shift(0.2*DOWN))
        self.play(Create(circle), run_time=2)
        AngleMAB = always_redraw(lambda:
            Angle(AM, AB, quadrant=(1,1), color=BLUE, radius=0.5, stroke_width=5)
        )
        valueofAngleMAB = always_redraw(lambda:
            DecimalNumber(Angle(AM, AB, quadrant=(1,1)).get_value(degrees=True), unit=r"^{\circ}")
        )
        AngleAMB = always_redraw(lambda:
            RightAngle(MB, AM, quadrant=(1,-1), color=BLUE, length=0.4, stroke_width=5)
        )
        arcofangleMBA = always_redraw(lambda:
            Angle(BA, MB.copy().reverse_points(), quadrant=(1,1), color=DARK_BROWN, radius=0.75, stroke_width=5)
        )
        self.play(
            FadeIn(
                O, A, B, M, PointO, PointA, PointB, PointM,
                AB, AM, MB, AngleMAB, AngleAMB, arcofangleMBA,
                valueofAngleMAB
            ),
            run_time=3
        )
        self.wait(0)
        self.play(angleAOM.animate.set_value(179), rate_func=linear, run_time=10)
        self.wait()
```

**Comment by Musimatician** [comment] 2024-04-13 11:03
Dear Uwe Zimmermann, I really appreciate your help. Very nice.
I am new learner who is interested in Manim.
The code you sent me worked perfectly : Many thanks.

The thing is, I compared both codes yours and mine and I couldn't find my mistake.
Anyway thanks again, and I will try to post properly my future issues.
     On Saturday, April 13, 2024 at 12:45:16 PM GMT+3, Uwe Zimmermann ***@***.***> wrote:  
 
 


If you include code you need to properly format it in Markup editors like here on github or on Discord - where I would like to point you for better help and better discussions.

Your question is not an issue with the code base of Manim - it is caused by a misunderstanding on how Manim works and we gladly help you to learn more about Manim here: Where can I find more resources for learning Manim?

Your lines BA and BM are never added to the scene, therefore especially the updater of the line BM is never executed.

I am not sure why the always_redraw on your DecimalNumber() does not work, but here is a working version of your code:
class geometry (Scene) :    def construct (self) :        angleAOM = ValueTracker(20)        circle = Circle().scale(3)        circle.set(color=RED, stroke_width=6)        O = Dot(circle.get_center())        A = Dot(circle.point_at_angle(0*DEGREES))        B = Dot(circle.point_at_angle(180*DEGREES))        M = always_redraw(lambda:            Dot(circle.point_at_angle(angleAOM.get_value()*DEGREES), color=BLUE)        )        AB = Line(A.get_center(), B.get_center()).set_color(PURE_BLUE)        BA = Line(B.get_center(), A.get_center()).set_color(PURE_BLUE)        AM = always_redraw(lambda:            Line(A.get_center(), M.get_center(), color=GREEN, stroke_width=5)        )        MA = always_redraw(lambda:            Line(M.get_center(), A.get_center(), color=GREEN, stroke_width=5)        )        MB = always_redraw(lambda:            Line(M.get_center(), B.get_center(), color=YELLOW, stroke_width=5)        )        BM = always_redraw(lambda:            Line(B.get_center(), M.get_center(), color=YELLOW, stroke_width=5)        )        PointO = Text("O", weight=BOLD, color=GOLD).next_to(O, DOWN).scale(0.5).shift(0.2*UP)        PointA = Text("A", weight=BOLD, color=GOLD).next_to(A, RIGHT).scale(0.5).shift(0.2*LEFT)        PointB = Text("B", weight=BOLD, color=GOLD).next_to(B, LEFT).scale(0.5).shift(0.2*RIGHT)        PointM = always_redraw(lambda: Text("M", weight=BOLD, color=BLUE).next_to(M, UP).scale(0.5).shift(0.2*DOWN))        self.play(Create(circle), run_time=2)        AngleMAB = always_redraw(lambda:            Angle(AM, AB, quadrant=(1,1), color=BLUE, radius=0.5, stroke_width=5)        )        valueofAngleMAB = always_redraw(lambda:            DecimalNumber(Angle(AM, AB, quadrant=(1,1)).get_value(degrees=True), unit=r"^{\circ}")        )        AngleAMB = always_redraw(lambda:            RightAngle(MB, AM, quadrant=(1,-1), color=BLUE, length=0.4, stroke_width=5)        )        arcofangleMBA = always_redraw(lambda:            Angle(BA, MB.copy().reverse_points(), quadrant=(1,1), color=DARK_BROWN, radius=0.75, stroke_width=5)        )        self.play(            FadeIn(                O, A, B, M, PointO, PointA, PointB, PointM,                AB, AM, MB, AngleMAB, AngleAMB, arcofangleMBA,                valueofAngleMAB            ),            run_time=3        )        self.wait(0)        self.play(angleAOM.animate.set_value(179), rate_func=linear, run_time=10)        self.wait()

**Comment by uwezi** [comment] 2024-04-13 11:21
> Dear Uwe Zimmermann, I really appreciate your help. Very nice. I am new learner who is interested in Manim. The code you sent me worked perfectly : Many thanks. The thing is, I compared both codes yours and mine and I couldn't find my mistake. 

- `arcofangleMBA` did not have an `always_redraw`
- I changed the argument of the `DecimalNumber()` to actually regenerate an angle and get the numeric value inline

**Comment by Musimatician** [comment] 2024-04-13 11:47
Infinitly grateful.

**Comment by behackl** [comment] 2024-04-20 09:04
Closing this, not an issue with the library.

**Closed by behackl** 2024-04-20 09:04 UTC
