### ISSUE TITLE
Improve startup time due to imports

### ISSUE THREAD

**Issue by Freyert** [ManimCommunity/manim#2542] opened 2022-02-13 02:17 UTC
## Enhancement proposal

First off: I really love this library, and I don't know too much about the internals so please bear that ignorance in mind! Really I'm just curious and would love to contribute improvements with appropriate mentorship!

----

I've noticed that it can take a long time for the `manim` tool to actually load and start rendering. Using `py-spy` I was able to see that the majority of the time spent running `manim` was spent loading dependencies in `manim/__init__.py`.

![image](https://user-images.githubusercontent.com/449155/153735203-5c025fe8-f938-4d76-b6da-9912d746df87.png)

This slow start up time was compounded for me because I typically ran `manim` inside of `poetry` using `poetry run manim`. The more optimal way to run this would be to use `poetry shell` and then run `manim` inside the prepared environment.

I _think_ most of the imports come from [`manim/__init__.py`](https://github.com/ManimCommunity/manim/blob/main/manim/__init__.py#L15-L109).  Why are all those imports there? Shouldn't the manim script I've written manage the necessary imports?

Is this something where the CLI is acting like a library as well; re-exporting modules? If the responsibilities of CLI and library were more distinct would the CLI need to perform all of these imports before rendering?

## Additional comments
System: Mac OSX 11.2.3 (Big Sur)
Model Name:	Mac mini
Model Identifier:	Macmini8,1
Processor Name:	Quad-Core Intel Core i3
Processor Speed:	3.6 GHz
Number of Processors:	1
Total Number of Cores:	4
L2 Cache (per Core):	256 KB
L3 Cache:	6 MB
Memory:	8 GB

I rendered the following tutorial script:

```python
from manim import *


class CreateCircle(Scene):
    def construct(self):
        circle = Circle()  # create a circle
        circle.set_fill(PINK, opacity=0.5)  # set the color and transparency
        self.play(Create(circle))  # show the circle on screen
```

with the following commands:

`sudo time py-spy record -o profile.svg -- manim -pql ./quickstart/__init__.py CreateCircle`

The timing results are as follows:

`2.14 real         1.26 user         0.68 sys`

This is the profiling flamegraph SVG:
![profile](https://user-images.githubusercontent.com/449155/153735375-255182eb-ff0c-46a1-89de-4ca376167cfd.svg)

**Comment by naveen521kk** [comment] 2022-02-17 15:20
I think this is a duplicate of https://github.com/ManimCommunity/manim/issues/1766 and I think this should require some discussion.

**Closed** 2022-02-27 14:21 UTC
Labels: enhancement, performance
