### ISSUE TITLE
Coloring subscripts/superscripts gets messed up

### ISSUE THREAD

**Issue by sudgy** [ManimCommunity/manim#209] opened 2020-07-21 04:34 UTC
Consider the following scene:

```python
class TestColor(Scene):
    def construct(self):
        t = TexMobject("e_1", "^2")
        t[0].set_color(RED)
        self.add(t)
        self.wait(1)
```

When rendered, this scene makes the 2 red, but not the 1.  You can workaround the issue by splitting it in three parts and write the superscript first, but it's still an annoying bug.

**Comment by kilacoda** [comment] 2020-07-21 05:07
I don't think this is a bug, but rather the way TexMobjects are indexed by manim. The index is 0 for `e^2` and 1 for `1` .
![image](https://user-images.githubusercontent.com/65204531/88014884-9450fa80-cb3d-11ea-85a4-85c7a7c8122f.png)

**Comment by sudgy** [comment] 2020-07-21 05:12
Well, this is what I originally encountered, which seems more like a bug:

```python
class TestColor(Scene):
    def construct(self):
        t = TexMobject("e_1", "^2")
        t.set_color_by_tex_to_color_map({"e_1": RED})
        self.add(t)
        self.wait(1)
```

Here, I explicitly ask for e_1 to be colored red, and it still does the same thing.

**Comment by leotrs** [comment] 2020-08-15 17:01
@sudgy thanks for reporting it. Your first code chunk looks fine to me, but the second one could be improved. It probably has to do with how `set_color_by_tex_to_color_map` works. Any takers for fixes or PRs?

**Comment by leotrs** [comment] 2020-11-12 16:52
Can confirm this looks like a bug. Below, the desired colors of 1 and 2 are reversed.

```python
class TestColor(mn.Scene):
    def construct(self):
        t = mn.MathTex(r"e", r"_1", r"^2")
        t.set_color_by_tex_to_color_map({r"e": mn.YELLOW, r"2": mn.RED, r"1": mn.BLUE})
        self.add(t)
        self.wait(1)
```

![2020-11-12-115225_113x139_scrot](https://user-images.githubusercontent.com/1096704/98970103-8f91c700-24dd-11eb-91c4-0e8fc056be77.png)


 Cc. @ManimCommunity/latex

**Comment by cobordism** [comment] 2020-11-17 15:28
Sometimes you just have to try by hand. You'd create `t = MathTex(r"e_1^2")` and then experiment with the individual pieces - addressing them by index like: `t[0][2]`.

The issue is that as far as the svg image goes, `e_1^2` and `e^2_1` are the same  and so figuring out in maim which part of the svg came from the `_1` and which came from the `^2` is harder than it looks.
The current system is very basic and provides convenient access when it works... but in general you might have to do it by hand.

Until we have a much more sophisticated system of matching glyphs/paths in the svg with strings in the argument to Tex(), we should probably document how you can address each individual glyph[m][n].

**Comment by leotrs** [comment] 2020-11-18 23:14
Thanks @cobordism, good point. I can confirm that the following code seems to yield the desired output. 

```python
class TestColor(Scene):
    def construct(self):
        t = TexMobject("e", "^2", "_1")
        t.set_color_by_tex_to_color_map({"e": RED, "1": RED})
        self.add(t)
        self.wait(1)
```

I think this is a fair workaround for the time being, and that anything better would require a massive rewrite. So I'm closing this for now.

**Closed by leotrs** 2020-11-18 23:14 UTC
Labels: bug, help wanted
