### ISSUE TITLE
Text issue

### ISSUE THREAD

**Issue by samcoveney** [ManimCommunity/manim#3449] opened 2023-11-11 23:21 UTC
## Description of bug / unexpected behavior
I installed manim via instructions on https://docs.manim.community/en/stable/installation/conda.html and while much of it works, anything using ```Text()```, including using ```Table```, fails.

For example:

```py
from manim import *
Text(1)
```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[5], line 1
----> 1 Text("1")

File ~/miniconda3/envs/pymanim/lib/python3.11/site-packages/manim/mobject/text/text_mobject.py:486, in Text.__init__(self, text, fill_opacity, stroke_width, color, font_size, line_spacing, font, slant, weight, t2c, t2f, t2g, t2s, t2w, gradient, tab_width, warn_missing_font, height, width, should_center, disable_ligatures, **kwargs)
    483     self.line_spacing = self._font_size + self._font_size * self.line_spacing
    485 color = Color(color) if color else VMobject().color
--> 486 file_name = self._text2svg(color)
    487 PangoUtils.remove_last_M(file_name)
    488 super().__init__(
    489     file_name,
    490     fill_opacity=fill_opacity,
   (...)
    496     **kwargs,
    497 )

File ~/miniconda3/envs/pymanim/lib/python3.11/site-packages/manim/mobject/text/text_mobject.py:814, in Text._text2svg(self, color)
    811     width = config["pixel_width"]
    812     height = config["pixel_height"]
--> 814     svg_file = manimpango.text2svg(
    815         settings,
    816         size,
    817         line_spacing,
    818         self.disable_ligatures,
    819         str(file_name.resolve()),
    820         START_X,
    821         START_Y,
    822         width,
    823         height,
    824         self.text,
    825     )
    827 return svg_file

TypeError: Argument 'size' has incorrect type (expected int, got float

## System specifications

<details><summary>System Details</summary>

- Ubuntu 20.04.6 LTS
- Python 3.11.6 | packaged by conda-forge
- Manim Community v0.17.3
- TeX, Version 3.14159265 (TeX Live 2019/Debian) (preloaded format=tex)

**Comment by uwezi** [comment] 2023-11-11 23:41
This is apparently a duplicate of [https://github.com/ManimCommunity/ManimPango/issues/106](https://github.com/ManimCommunity/ManimPango/issues/106) and #3403 

Try if `pip install manimpango --force` helps.

**Comment by behackl** [comment] 2023-11-12 00:44
Indeed, this has been fixed in today's release of `v0.18.0` -- which should also be available natively via conda soon. You can also upgrade the python package manually.

Nothing else left to do here.

**Closed by behackl** 2023-11-12 00:44 UTC
