### ISSUE TITLE
Removing FadeInFromDown and FadeOutAndShiftDown

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#112] opened 2020-05-30 16:51 UTC
In my opinion they are completly useless since when `FadeInFrom`and `FadeOutAndShift `are called `direction = DOWN` is set by default. 

(And `FadeInFrom(mobject, direction = DOWN)` , `FadeOutAndShift(mobject, direction = DOWN)` are equivalent)

EDIT : I mixed up `FadeIn `and `FadeInFrom`. I'm talking about the latter; `FadeIn `is fine

**Comment by leotrs** [comment] 2020-05-30 17:28
Paging @XorUnison, what do you think about this in terms of convenience?

**Comment by PhilippImhof** [comment] 2020-05-30 17:49
From a user's perspective, it is strange to have specific functions for fading from one direction, but not from others. Even though I am too small a sample to be representative, I would prefer a generic function with the direction given as a parameter and a reasonable default.

**Comment by XorUnison** [comment] 2020-05-30 22:22
I mean, there's also the factor that manim used to have this whole convoluted process of mixing animations.
Now we can just do:
```python
self.play(mobject.rotate,np.pi,
          mobject.shift,DOWN)
```
And call it a day.

That's because manim can now mash and mix all properly coded methods of mobjects such as shift and rotate. Works with custom stuff too.

So what we should do is probably nuke those archaic methods, and instead add mobject.fade_out and mobject.fade_in. Then we can just go the much better way of:
```python
self.play(mobject.fade_out,np.pi,
          mobject.shift,DOWN)
```
And any other combination we may want.

> (And FadeIn(mobject, direction = DOWN) , FadeOutAndShift(mobject, direction = DOWN) are equivalent)

This... however doesn't seem to be the case on my end? FadeIn is FadeIn for me, direction passed or not. I see no way for FadeIn to digest a direction into anything meaningful either.

**Comment by PgBiel** [comment] 2020-05-31 02:49
> Now we can just do:
Hol' up, have we fixed the multiple animations on one mobject issue already? On which PR?

**Comment by XorUnison** [comment] 2020-05-31 03:59
Which issue exactly? I see no such open issue and this is currently possible in vanilla manim, and I've not been able to find any issues with it either. What's the problem?

**Comment by PgBiel** [comment] 2020-05-31 04:01
Oh... I was thinking of the "bug" that doesn't let you do
```py
self.play(Rotating(mobj), FadeIn(mobj))
```
(for e.g.)

**Comment by XorUnison** [comment] 2020-05-31 04:04
Right, this has been a thing for a good long while, and I'm not even sure what the issue is, nor if it can and should be fixed.
But as I said, the syntax I highlighted above does now work. But as far as I know it requires mobject.methods to work with.

**Comment by leotrs** [comment] 2020-05-31 16:37
So it seems that there's agreement on removing `FadeInFromDown` and `FadeOutAndShiftDown` and other similar methods.

Now, do we want to just nuke them or deprecate them (ie issue a DeprecationWarning for now and delete them later)?

**Comment by PhilippImhof** [comment] 2020-05-31 17:48
I prefer the latter. It is always frustrating when stuff disappears without prior notice. If nobody else is currently on it, I might be able to prepare a PR to solve this issue.

**Comment by leotrs** [comment] 2020-06-07 16:34
@huguesdevimeux, or anyone else, are there any volunteers to write a PR that deprecates `FadeInFromDown`, `FadeOutAndShiftDown`, and other similar methods?

**Comment by huguesdevimeux** [comment] 2020-06-12 16:01
@PhilippImhof Feel free to submit a PR :)

**Comment by PhilippImhof** [comment] 2020-06-12 16:43
> @PhilippImhof Feel free to submit a PR :)

Haha, j'allais dire la même chose.... 😊 I'll have a look at it, but I 'm not sure whether I got all of it right.

**Comment by leotrs** [comment] 2020-06-13 01:24
> but I 'm not sure whether I got all of it right.

That's what code reviews are for! Looking forward to your PR.

**Closed** 2020-06-13 14:35 UTC
Labels: cleaning, help wanted, refactor/rework
