### ISSUE TITLE
Click Refactor - Traceback doesn't show on Ctrl+C

### ISSUE THREAD

**Issue by jsonvillanueva** [ManimCommunity/manim#1207] opened 2021-03-31 11:57 UTC
During the times of Argparse, Ctrl+C would show the traceback. Click has its own exception handling which conflicts with how Argparse would've handled this previously. Instead it just shows `Aborted!` prior to ending program execution. 

The solution to this should be on this page: https://click.palletsprojects.com/en/7.x/exceptions/?highlight=aborted#what-if-i-don-t-want-that but needs to consider our entry point.

**Comment by behackl** [comment] 2023-10-26 11:02
Is there a case where we actually want to have the full traceback -- does this not work as intended as-is? Closing this for now (but we can reopen in case the issue still exists and can be specified more precisely).

**Closed by behackl** 2023-10-26 11:02 UTC
Labels: enhancement
