### ISSUE TITLE
Refactor Arc (add setters, convert all attributes to properties)

### ISSUE THREAD

**Issue by ponmike92** [ManimCommunity/manim#853] opened 2020-12-11 09:07 UTC
I struggled with current manim Arc class realisation for the following reasons:
1. I can't rely on attributes of Arc object. Points of object can be modified by shift, move_to, rotate or other methods but attributes stays the same.

2. I can't simply set new angle or radius or other Arc properties. I have to recreate object with new attributes.

3. I don't have enough Arc properties which can be useful while using Arc object like start vector, end_vector, or end angle.

Thats why I wrote my own realisation of Arc class.

Questions I would like to discuss:
1. Pros and cons of this realisation?
2. How about removing all attributes which can be calculated through points of mobject? Like start, end, tangent, angle, arc_center, radius, num_components and so on..

## code
```python
class Arc(TipableVMobject):

    def __init__(
        self,
        start_angle=0,
        angle=TAU / 4,
        radius=1.0,
        num_components=9,
        arc_center=ORIGIN,
        **kwargs
    ):

        TipableVMobject.__init__(self, **kwargs)
        self.set_points(start_angle, angle, radius, num_components, arc_center)

    def set_points(self, start_angle, angle, radius, num_components, arc_center):
        self._set_pre_positioned_points(start_angle, angle, num_components)
        self.scale(radius, about_point=arc_center)
        self.shift(arc_center)

    def reappend_points(self, start_angle=None, angle=None, radius=None, num_components=None, arc_center=None):
        if start_angle is None: start_angle = self.start_angle
        if angle is None: angle = self.angle
        if radius is None: radius = self.radius
        if num_components is None: num_components = self.num_components
        if arc_center is None: arc_center = self.arc_center

        self.clear_points()
        self.set_points(start_angle, angle, radius, num_components, arc_center)

    def _set_pre_positioned_points(self,
                                start_angle=None,
                                angle=None,
                                num_components=None,
                                ):
        anchors = np.array(
            [
                np.cos(a) * RIGHT + np.sin(a) * UP
                for a in np.linspace(
                    start_angle, start_angle + angle, num_components
                )
            ]
        )
        # Figure out which control points will give the
        # Appropriate tangent lines to the circle
        d_theta = angle / (num_components - 1.0)
        tangent_vectors = np.zeros(anchors.shape)
        # Rotate all 90 degress, via (x, y) -> (-y, x)
        tangent_vectors[:, 1] = anchors[:, 0]
        tangent_vectors[:, 0] = -anchors[:, 1]
        # Use tangent vectors to deduce anchors
        handles1 = anchors[:-1] + (d_theta / 3) * tangent_vectors[:-1]
        handles2 = anchors[1:] - (d_theta / 3) * tangent_vectors[1:]
        self.set_anchors_and_handles(anchors[:-1], handles1, handles2, anchors[1:])

    # getters
    @property
    def arc_center(self):
        a1, h1, h2, a2 = self.points[:4]

        if np.all(a1 == a2):
            return a1
        # Tangent vectors
        t1 = h1 - a1
        t2 = h2 - a2
        # Normals
        n1 = rotate_vector(t1, TAU / 4)
        n2 = rotate_vector(t2, TAU / 4)
        try:
            return line_intersection(line1=(a1, a1 + n1), line2=(a2, a2 + n2))
        except Exception:
            return np.array(ORIGIN)

    @property
    def start(self):
        return self.get_start()

    @property
    def end(self):
        return self.get_end()

    @property
    def start_vector(self):
        return self.start - self.arc_center

    @property
    def end_vector(self):
        return self.end - self.arc_center

    @property
    def start_angle(self):
        return angle_of_vector(self.start_vector)

    @property
    def end_angle(self):
        return angle_of_vector(self.end_vector)

    @property
    def angle(self):
        return signed_angle_between(self.start_vector, self.end_vector)    

    @property
    def radius(self):
        return get_norm(self.arc_center - self.start)

    @property
    def num_components(self):
        return int(len(self.points) / 4) + 1

    #setters
    @start_angle.setter
    def start_angle(self, angle):
        delta = angle - self.start_angle
        self.rotate(delta, about_point=self.arc_center)
        return self

    @angle.setter
    def angle(self, angle):
        # make sure angle -360 .. 360 degrees
        if angle > TAU: angle = angle % TAU
        if angle < -TAU: angle = angle % -TAU

        self.reappend_points(angle=angle)
        return self

    @radius.setter
    def radius(self, radius):
        self.scale(radius / self.radius, about_point=self.arc_center)
        return self

    @arc_center.setter
    def arc_center(self, point):
        self.shift(point - self.arc_center)
        return self

    # for back compatability with current version of manim 
    def set_start_angle(self, angle): self.start_angle = angle
    def set_angle(self, angle): self.angle = angle
    def set_radius(self, radius): self.radius = radius
    def move_arc_center_to(self, point): self.arc_center = point
```

**Comment by eulertour** [comment] 2020-12-11 10:20
In general relying on the array of points will yield more accurate results than relying on stored properties, since only the points are used during rendering. However, properties can't be derived from points in general, so I'd consider this to be a step in the wrong direction.

Non-stylistic properties are generally only accurate after a Mobject has been created and before it's been modified, which is what leads to the pattern of creating new ones with different properties in the first place, although this may not be clear from the documentation we have currently.

**Comment by ponmike92** [comment] 2020-12-11 12:25
> However, properties can't be derived from points in general, so I'd consider this to be a step in the wrong direction.

Agree. But if it comes to arc_center, tangent, start, end, radius .. they all can be easily retrieved through points. If it comes to more complicated object properties - they could be saved as attributes.

**Comment by leotrs** [comment] 2020-12-11 13:12
> properties can't be derived from points in general

I don't understand what you mean by this, can you please clarify?

PS @cobordism and I started working on a PR to get rid of most getters and setters

**Comment by ponmike92** [comment] 2020-12-11 18:48
> I don't understand what you mean by this, can you please clarify?

I can. 
Good example of determining property through points is get_arc_center() method in Arc class. 

```python
    def get_arc_center(self):
        """
        Looks at the normals to the first two
        anchors, and finds their intersection points
        """
        # First two anchors and handles
        a1, h1, h2, a2 = self.points[:4]

        if np.all(a1 == a2):
            # For a1 and a2 to lie at the same point arc radius
            # must be zero. Thus arc_center will also lie at
            # that point.
            return a1
        # Tangent vectors
        t1 = h1 - a1
        t2 = h2 - a2
        # Normals
        n1 = rotate_vector(t1, TAU / 4)
        n2 = rotate_vector(t2, TAU / 4)
        try:
            return line_intersection(line1=(a1, a1 + n1), line2=(a2, a2 + n2))
```

If im not mistaken @eulertour wanna say that for more complicated objects will be hard to create algorithm of retrieving one of its property by its points. 

To avoid misunderstanding:
**@property python decorator** and **object properties** - are two different instances. The latter is width, arc_center, start, end, height, corner_roundness, angle, size and so on.

**Comment by eulertour** [comment] 2020-12-13 21:42
@leotrs One way to see it clearly is that there's no way to rederive a Circle's radius after transforming it to a Square.

@ponmike92 There are already Mobject properties that can always be derived from their data, but they're never class-specific. Things like, height, width, extreme points, style properties, etc. But trying to get the library to make attributes like radius work sensibly depending on whether or not they can be derived from data won't work without a lot of restructuring and wouldn't have much use, since the user can keep track of them manually.

If anything, I might be in favor of removing class-specific attributes from Mobjects so people don't get confused when they're sometimes wrong.

**Comment by ponmike92** [comment] 2020-12-14 05:54
> If anything, I might be in favor of removing class-specific attributes from Mobjects so people don't get confused when they're sometimes wrong.
@eulertour you mean that some classes have properties which are presented in both styles? Like cls.get_start() method and cls.start attribute

**Comment by eulertour** [comment] 2020-12-14 06:03
Some might, but what I mean is that all of them will retain their attributes even after they aren't accurate anymore.

**Comment by XorUnison** [comment] 2020-12-14 06:35
> One way to see it clearly is that there's no way to rederive a Circle's radius after transforming it to a Square.

I'm not seeing how this would be an issue? Generally after such a transformation, an according accessible `Circle` object shouldn't even exist anymore, since like you said, it was transformed to something else. Trying to access the original `Circle` then is an user error.

> If anything, I might be in favor of removing class-specific attributes from Mobjects so people don't get confused when they're sometimes wrong.

I strongly disagree, assuming I even understood you correctly. Removing class-specific attributes would make the manim library much more complicated to use, less powerful and less useful. Users would have to implement all sorts of crazy personal math workarounds to do stuff.
I get that making properties that are always right is an uphill battle, but one that's worth it.

**Comment by eulertour** [comment] 2020-12-14 06:44
> I'm not seeing how this would be an issue? Generally after such a transformation, an according accessible Circle object shouldn't even exist anymore, since like you said, it was transformed to something else. Trying to access the original Circle then is an user error.

You could look at it this way, in which case you'd consider the difficulty from the first point of [the original comment](https://github.com/ManimCommunity/manim/issues/853#issue-762111872) to just be user error. It's less confusing if the software doesn't appear to have an accurate result while not actually doing so.

> Users would have to implement all sorts of crazy personal math workarounds to do stuff.

Why do you think this? The current attributes only store data that the user provides them anyway, so that data is already available anyway.

**Comment by XorUnison** [comment] 2020-12-14 08:45
> You could look at it this way, in which case you'd consider the difficulty from the first point of [the original comment](https://github.com/ManimCommunity/manim/issues/853#issue-762111872) to just be user error. It's less confusing if the software doesn't appear to have an accurate result while not actually doing so.

Correct, but the point would be for it to appear to have accurate results, while actually having those results correctly.

> Why do you think this? The current attributes only store data that the user provides them anyway, so that data is already available anyway.

Yeah but if you scale an arc or transform one arc into another arc, all of the interpolated arcs in between are valid and sometimes you need their values. I think this because I've been there, so it's not a hypothetical either. Case in point, my third video employs transformations of tilings while also displaying the exclusion zones of such tiles while they transform. I'll keep the detail at a minimum, but these exclusion zones can only be properly made from an `ArcPolygon`, by accessing the contained arcs and their angles as they are at that exact moment in the transformation.
And since `Arc.angle` currently doesn't have a real good property implementation I basically had to write what this property method would do externally, then have my class take these arcs, throw them into said self-created method to then work from there. I had to do this for a few different things as well. Or in other words this accurate access to class properties at any time like in the middle of a transformation is so fundamental that I can promise you many people will have written according methods to circumvent this issue many times separately. And the analysis of what happens during a transform from one object to another is a pretty general use case too.

Hence me already having been in the spot to make "crazy personal math workarounds", and hence my comment. Having this standardized in all classes would make manim vastly more powerful and easy to use all at the same time.

**Comment by eulertour** [comment] 2020-12-14 09:45
Closing this since the cause of the issue has been cleared up.

**Closed by eulertour** 2020-12-14 09:45 UTC
Labels: enhancement
