### ISSUE TITLE
Camera doesn't move when ApplyMethod is involved.

### ISSUE THREAD

**Issue by MulleDK19** [ManimCommunity/manim#713] opened 2020-11-15 18:46 UTC
## Description of bug / unexpected behavior

When `ApplyMethod` is involved in animation, the camera fails to move in a `MovingCameraScene`

## Expected behavior

The camera moves as instructed.

## How to reproduce the issue

<details><summary>Working code</summary>

```py
class TestScene(MovingCameraScene):
    def construct(self):
        c = Circle()
        c.shift(UR * 2)
        c.set_fill(ORANGE, opacity=1)
        self.add(c)
        gc = c.get_center()
        gcw = c.get_width()
        # Fails to move when using ApplyMethod.
        self.play(
            self.camera_frame.move_to, gc,
            self.camera_frame.set_width, gcw * 2,
            rate_func = smooth,
            run_time = 1)
        self.wait(1)
```

</details>

Put either of the methods in `self.play` inside an `ApplyMethod` and the camera won't move. It'll still zoom, but not move.
Not so much a problem when using `self.play` as `ApplyMethod` is not required there, but makes it impossible to use with eg. `AnimationGroup`.

It doesn't matter whether you put the `move_to` or the `set_width` in an `ApplyMethod`.

<details><summary>Failing code</summary>

```py
        self.play(
            ApplyMethod(self.camera_frame.move_to, gc),
            self.camera_frame.set_width, gcw * 2,
            rate_func = smooth,
            run_time = 1)
```

```py
        self.play(
            self.camera_frame.move_to, gc,
            ApplyMethod(self.camera_frame.set_width, gcw * 2),
            rate_func = smooth,
            run_time = 1)
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

Without `ApplyMethod`

![image](https://user-images.githubusercontent.com/3169809/99193731-2a5b0180-277b-11eb-9fb4-c7fbd05d1295.png)

With `ApplyMethod`

![image](https://user-images.githubusercontent.com/3169809/99193742-3e9efe80-277b-11eb-9b9a-a6fe279e9a1e.png)

</details>

## Additional comments
Command line used, just in case.

```
manim main.py TestScene --production_quality -p --flush_cache --disable_caching
```

**Comment by behackl** [comment] 2022-05-28 07:11
Duplicate of #722 (which describes the underlying issue better), and works when using the animate syntax with chained method calls. Closing.

**Closed by behackl** 2022-05-28 07:11 UTC
Labels: duplicate/wontfix, bug
