### ISSUE TITLE
 [BUG-TEXT]   t2s is broken with PangoText

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#673] opened 2020-11-03 11:22 UTC
```python
class Test(Scene):
    def construct(self):
            paragraph = Text("this is some text", t2s={"text": ITALIC})
            self.play(ShowCreation(paragraph))
```
generates this : 
![image](https://user-images.githubusercontent.com/36239975/97979225-16a0ba00-1dcf-11eb-9616-327fc60d687d.png)
("text" at the end is neither in Italic or displayed). 

Could someone else confirm this ? 

cc @naveen521kk

**Comment by naveen521kk** [comment] 2020-11-03 11:30
Duplicate of  #636

**Closed by naveen521kk** 2020-11-03 11:30 UTC
Labels: bug

**Comment by huguesdevimeux** [comment] 2020-11-03 11:35
sorry for this
