### ISSUE TITLE
v0.2.1 Roadmap

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#909] opened 2021-01-06 22:57 UTC
# Things to discuss

# Things to implement
* Jupyter notebook support #895

_Feel free to edit this message and add further points!_

**Comment by clarfonthey** [comment] 2021-01-09 00:08
Definitely going to want to get #907 in 0.2.1 as well.

**Comment by ponmike92** [comment] 2021-01-09 12:06
Look forward to have ability to create custom animations for mobjects somehow like so:


```python
class UserVMobject(VMobject):
    def ShowCreation(self, alpha, *args, **kwargs):
        # logic here

class UserScene(Scene):
    def construct(self):
        mob = UserVMobject()

        self.play(
            mob.ShowCreation(run_time=3, rate_func=linear)
        )
``

**Comment by aman17009** [comment] 2021-01-09 13:45
An intuitive API for creating custom Mobjects.

**Comment by behackl** [comment] 2021-01-09 14:13
> An intuitive API for creating custom Mobjects.

This is very unspecific, could you please give some details what you have on your mind (preferably in a separate issue).

**Comment by behackl** [comment] 2021-01-09 14:19
> Look forward to have ability to create custom animations for mobjects somehow like so:
> 
> ```python
> class UserVMobject(VMobject):
>     def ShowCreation(self, alpha, *args, **kwargs):
>         # logic here
> 
> class UserScene(Scene):
>     def construct(self):
>         mob = UserVMobject()
> 
>         self.play(
>             mob.ShowCreation(run_time=3, rate_func=linear)
>         )
> ``
> ```

As long as your custom `ShowCreation` returns an animation, I don't see why this wouldn't work already.

**Comment by naveen521kk** [comment] 2021-01-10 02:59
I am hiding all the comments above. Please keep the discussion related to the issue. You can create one if it doesn't exist.

**Comment by ponmike92** [comment] 2021-01-11 05:56
Things to implement: Unit conversion support #742 

Did not find how attach to main message.

**Comment by clarfonthey** [comment] 2021-01-11 06:38
(Only repo maintainers can edit issue descriptions)

**Comment by behackl** [comment] 2021-01-31 02:25
Final preparations for the upcoming release:

- There are some ([somewhat] easy looking) bugfixes which I think would be good to have for the release (#983, #981 (?), #972 if the problem with the tests can be resolved soon)
- I'd also really like to have #977; there already is one positive review -- if there are no further comments or objections, I'd merge it at some point tomorrow

Regarding the changelog: given that we haven't really advanced on #927 (especially regarding categorization), I volunteer to prepare a suggestion at some point tomorrow. I don't think that there are any serious breaking changes since v0.2.0, so I don't think that we will have to compile a lot of supplementary notes., if any at all -- the commit messages should pretty much be sufficient. :-)

**Comment by WampyCakes** [comment] 2021-01-31 19:35
@behackl Regarding #981, someone other than me needs to test it on Windows (and Mac would probably be a good idea too). Then it can be merged. I think @eulertour confirmed it works on Linux, and it works on Windows for me so this should just be additional checking to make sure before merging.

**Comment by sparshg** [comment] 2021-02-01 16:31
I think #951 should also be easy to fix as @behackl said

**Comment by behackl** [comment] 2021-02-02 09:21
Closed by our latest release.

**Closed by behackl** 2021-02-02 09:21 UTC
Labels: release
