### ISSUE TITLE
Colors displayed incorrectly when overlapping with axes

### ISSUE THREAD

**Issue by reubenadams** [ManimCommunity/manim#1464] opened 2021-05-04 16:22 UTC
## Description of bug / unexpected behavior
The color of lines produced by the method `get_line_graph` of an `Axes()` object is incorrect when the line overlaps with the axes or gridlines.

## Expected behavior
I expected both lines below to be yellow. However, the one called `bad_line` is displayed green even though the line color is specified as yellow.

## How to reproduce the issue
Run below code.

```py
class LineGraph(Scene):
    def construct(self):
        plane = NumberPlane()
        good_line = plane.get_line_graph(x_values=[-3, 1],
                                         y_values=[-2, 2],
                                         line_color=YELLOW)
        bad_line = plane.get_line_graph(x_values=[0, 2, 2, 4],
                                        y_values=[0, 0, 2, 2],
                                        line_color=YELLOW)
        self.add(plane, good_line, bad_line)
```

## Additional media files
![LineGraph_ManimCE_v0 6 0](https://user-images.githubusercontent.com/49562604/117035711-ee096680-ad04-11eb-9725-96fe0351b992.png)

## System specifications
- OS: Windows 10
- RAM: 4.0 GB
- Python version: 3.9.4

**Comment by abhi3019** [comment] 2021-05-05 04:16
Thanks for filing this issue! I can reproduce it locally on master. The issue seems to be with the `z_index` here
https://github.com/ManimCommunity/manim/blob/6d8e8a5bcf6eb6df9b4942a953104ce21f98bc4c/manim/mobject/coordinate_systems.py#L355
I think I was just testing with the `z_index` while working on the PR and forgot to remove / overlooked it. It is unnecessary (and actually bad since it pushes the `line_graph` behind the `NumberPlane` / `Axes`) and should be deleted. 

Removing this line seems to fix the issue, but I'm really surprised why `z_index` is messing up with the colors.

**Comment by JeroSQ** [comment] 2021-05-29 22:15
I think a 'good first issue' label should be added to this issue

**Comment by vasek123** [comment] 2021-08-23 13:05
Hello, I removed the line of code as suggested by @abhi3019. This seems to have fixed the issue.

**Comment by Rudransh24** [comment] 2021-08-29 18:07
hi! is this issue still open or did the merged PR solve it already?
I am new to open source so I was looking for some beginner issues.

**Comment by Darylgolden** [comment] 2021-09-22 11:41
I believe it's closed. Sorry for the confusion!

**Closed by Darylgolden** 2021-09-22 11:41 UTC
Labels: good first issue, bug
