### ISSUE TITLE
Transforming Text a into Text b and back

### ISSUE THREAD

**Issue by thistlillo** [ManimCommunity/manim#1468] opened 2021-05-05 14:16 UTC
## Description of bug / unexpected behavior
Please consider the following code:

```py
class TextCameraNW(MovingCameraScene):
    def construct(self):
        a = Text('First string')
        b = Text('Second, longer, much longer string')
        
        self.add(a)
        self.wait(0.5)
        self.play(Transform(a, b))
        self.wait(1)
        self.play(Transform(b, a))
```
The code should show two animations. The first turning `Text a` into `Text b`, the second transforming `Text b` back to `Text a`. However, on my installation, only the first animation is shown. The second transformation is not built: `Text b` is simply substituted with `Text a`.

Consider this code:

```py
from manim import *

class TextCameraNW2(MovingCameraScene):
    def construct(self):
        a = Text('First string')
        b = Text('Second, longer, much longer string')
        c = Text('First string')   
        
        self.add(a)
        self.wait(0.5)
        self.play(Transform(a, b))
        self.wait(1)
        self.play(Transform(b, c))
```
In this case, the animation `self.play(Transform(b,c))` is not rendered correctly: `Text b` is shown in full length during the animation (basically it covers the animation) and disappears only when the animation is complete, thus uncovering `Text c`.

This is the first code I build with manim CE, so may be it is wrong. However, I prefer to ask.

## Expected behavior
I would expect two animations (`Transform`) to be played.

## How to reproduce the issue
See code above.
</details>

## Additional media files

<details><summary>Images/GIFs</summary>

https://user-images.githubusercontent.com/6717655/117154567-43547f00-adbc-11eb-8f4c-209e4160eb60.mp4
https://user-images.githubusercontent.com/6717655/117154569-43ed1580-adbc-11eb-864b-a552c88dd214.mp4

</details>

## Logs
<details><summary>Terminal output</summary>
The log corresponds to the first animation (the one without c).

```

[05/05/21 16:10:12] DEBUG    Animation with empty mobject                                              animation.py:62                    DEBUG    Hashing ...                                                                hashing.py:240                    DEBUG    Hashing done in 0.051830 s.                                                hashing.py:253                    DEBUG    Hash generated :  739343402_2763922376_821388084                           hashing.py:257                    INFO     Animation 0 : Using cached data (hash :                             cairo_renderer.py:100                             739343402_2763922376_821388084)
                    DEBUG    List of the first few animation hashes of the scene:                cairo_renderer.py:108                             ['739343402_2763922376_821388084']
                    DEBUG    Hashing ...                                                                hashing.py:240                    DEBUG    Hashing done in 0.168062 s.                                                hashing.py:253                    DEBUG    Hash generated :  843594667_40508619_2264766361                            hashing.py:257                    INFO     Animation 1 : Using cached data (hash :                             cairo_renderer.py:100                             843594667_40508619_2264766361)
                    DEBUG    List of the first few animation hashes of the scene:                cairo_renderer.py:108                             ['739343402_2763922376_821388084', '843594667_40508619_2264766361']
[05/05/21 16:10:13] DEBUG    Animation with empty mobject                                              animation.py:62                    DEBUG    Hashing ...                                                                hashing.py:240                    DEBUG    Hashing done in 0.147610 s.                                                hashing.py:253                    DEBUG    Hash generated :  843594667_2432241074_127001009                           hashing.py:257                    DEBUG    List of the first few animation hashes of the scene:                cairo_renderer.py:108                             ['739343402_2763922376_821388084', '843594667_40508619_2264766361',
                             '843594667_2432241074_127001009']
[05/05/21 16:10:14] INFO     Animation 2 : Partial movie file written in {'C:\\Users\\user_scene_file_writer.py:401                             o\\workspace\\python\\manim-ce\\media\\videos\\example\\1080p60\
                             \partial_movie_files\\TextCameraNW\\843594667_2432241074_1270010
                             09.mp4'}
                    DEBUG    Hashing ...                                                                hashing.py:240                    DEBUG    Hashing done in 0.282094 s.                                                hashing.py:253                    DEBUG    Hash generated :  843594667_52955409_359259835                             hashing.py:257                    DEBUG    List of the first few animation hashes of the scene:                cairo_renderer.py:108                             ['739343402_2763922376_821388084', '843594667_40508619_2264766361',
                             '843594667_2432241074_127001009', '843594667_52955409_359259835']
[05/05/21 16:10:16] INFO     Animation 3 : Partial movie file written in {'C:\\Users\\user_scene_file_writer.py:401                             o\\workspace\\python\\manim-ce\\media\\videos\\example\\1080p60\
                             \partial_movie_files\\TextCameraNW\\843594667_52955409_359259835
                             .mp4'}
                    DEBUG    Partial movie files to combine (4 files): ['C:\\Users\\user\ scene_file_writer.py:450                             \workspace\\python\\manim-ce\\media\\videos\\example\\1080p60\\p
                             artial_movie_files\\TextCameraNW\\739343402_2763922376_821388084
                             .mp4', 'C:\\Users\\user\\workspace\\python\\manim-ce\\media\
                             \videos\\example\\1080p60\\partial_movie_files\\TextCameraNW\\84
                             3594667_40508619_2264766361.mp4', 'C:\\Users\\user\\workspac
                             e\\python\\manim-ce\\media\\videos\\example\\1080p60\\partial_mo
                             vie_files\\TextCameraNW\\843594667_2432241074_127001009.mp4', 'C
                             :\\Users\\user\\workspace\\python\\manim-ce\\media\\videos\\
                             example\\1080p60\\partial_movie_files\\TextCameraNW\\843594667_5
                             2955409_359259835.mp4']
                    INFO                                                                      scene_file_writer.py:585                             File ready at C:\Users\user\workspace\python\manim-ce\media\videos\example\1080p60\TextCameraNW.mp4

                    INFO     Rendered TextCameraNW                                                        scene.py:217                             Played 4 animations```

</details>


## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)): Windows 10 Pro 20H2
- RAM: 16
- Python version (`python/py/python3 --version`): 3.8.8
- Installed modules (provide output from `pip list`):
argon2-cffi         20.1.0
async-generator     1.10
attrs               20.3.0
backcall            0.2.0
bleach              3.3.0
certifi             2020.12.5
cffi                1.14.5
chardet             4.0.0
click               7.1.2
click-default-group 1.2.2
cloudpickle         1.6.0
cloup               0.7.1
colorama            0.4.4
colour              0.1.5
commonmark          0.9.1
decorator           4.4.2
defusedxml          0.7.1
entrypoints         0.3
glcontext           2.3.3
idna                2.10
ipykernel           5.5.3
ipython             7.23.0
ipython-genutils    0.2.0
ipywidgets          7.6.3
jedi                0.18.0
Jinja2              2.11.3
jsonschema          3.2.0
jupyter             1.0.0
jupyter-client      6.1.12
jupyter-console     6.4.0
jupyter-core        4.7.1
jupyterlab-pygments 0.1.2
jupyterlab-widgets  1.0.0
manim               0.6.0
ManimPango          0.2.6
mapbox-earcut       0.12.10
MarkupSafe          1.1.1
matplotlib-inline   0.1.2
mistune             0.8.4
moderngl            5.6.4
moderngl-window     2.3.0
multipledispatch    0.6.0
nbclient            0.5.3
nbconvert           6.0.7
nbformat            5.1.3
nest-asyncio        1.5.1
networkx            2.5.1
notebook            6.3.0
numpy               1.20.2
packaging           20.9
pandocfilters       1.4.3
parso               0.8.2
pickleshare         0.7.5
Pillow              8.2.0
pip                 21.1.1
prometheus-client   0.10.1
prompt-toolkit      3.0.18
pycairo             1.20.0
pycparser           2.20
pydub               0.25.1
pyglet              1.5.16
Pygments            2.9.0
pyparsing           2.4.7
pyrr                0.10.3
pyrsistent          0.17.3
python-dateutil     2.8.1
pywin32             300
pywinpty            1.0.1
pyzmq               22.0.3
qtconsole           5.1.0
QtPy                1.9.0
requests            2.25.1
rich                6.2.0
scipy               1.6.3
Send2Trash          1.5.0
setuptools          52.0.0.post20210125
six                 1.15.0
spyder-kernels      2.0.2
terminado           0.9.4
testpath            0.4.4
tornado             6.1
tqdm                4.60.0
traitlets           5.0.5
typing-extensions   3.10.0.0
urllib3             1.26.4
watchdog            2.1.0
wcwidth             0.2.5
webencodings        0.5.1
wheel               0.36.2
widgetsnbextension  3.5.1
wincertstore        0.2
yapf                0.31.0
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020): Miktex 2.9
+ Installed LaTeX packages:
quite a lot - I will provide it if necessary.
</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
ffmpeg version 4.2.3 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 9.3.1 (GCC) 20200523
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100```
</details>

**Comment by kilacoda** [comment] 2021-05-05 14:31
This is not a bug, but intentional. `Transform(m1, m2)` morphs `m1` into `m2` while keeping the same variable name, for what you're trying to do, `ReplacementTransform`  would be a better choice.

**Comment by thistlillo** [comment] 2021-05-05 15:47
Thank you. I came back to delete this issue since I realized that. Sorry.

**Comment by kilacoda** [comment] 2021-05-05 15:50
> Thank you. I came back to delete this issue since I realized that. Sorry.

No, no need to delete! Closing it would be fine. Which I should have done anyway.

For any more questions feel free to use the discussions tab, or the [discord server](https://discord.gg/mMRrZQW)!

**Closed by kilacoda** 2021-05-05 15:50 UTC
