### ISSUE TITLE
.rotate() not working

### ISSUE THREAD

**Issue by Analytical1703** [ManimCommunity/manim#921] opened 2021-01-10 11:16 UTC
#921 
`nl = NumberPlane()

        dot_1 = Dot([0,0,0],color=PINK)
        dot_2 = Dot([2,2,0],color=RED)

        self.play(
            ShowCreation(nl),
            run_time=2
        )

        self.wait(1.5)

        self.play(
            FadeIn(dot_1),
            FadeIn(dot_2),
            run_time=2
        )
        self.wait(1.5)`

       `arrow = Arrow(dot_1,dot_2,buff=-0, color=YELLOW)
        self.play(
            ShowCreation(arrow),
            run_time=2
        )
        self.wait(2)

        for i in range(4):
            self.play(
                arrow.rotate(i*PI/4),
                run_time=3
            )
        self.wait(3)`

**ERROR** -:
It gives an error like this -: 

`Traceback (most recent call last):`

 ` File "c:\python38\lib\site-packages\manim\__main__.py", line 75, in main
    scene.render()`

  `File "c:\python38\lib\site-packages\manim\scene\scene.py", line 88, in render
    self.construct()`

  `File "L2.py", line 70, in construct
    self.play(
  File "c:\python38\lib\site-packages\manim\scene\scene.py", line 774, in play
    self.renderer.play(self, *args, **kwargs)
  File "c:\python38\lib\site-packages\manim\renderer\cairo_renderer.py", line 13, in wrapper
    func(self, scene, *args, **kwargs)`

 ` File "c:\python38\lib\site-packages\manim\utils\caching.py", line 24, in wrapper
    animations = scene.compile_play_args_to_animation_list(*args, **kwargs)`

  `File "c:\python38\lib\site-packages\manim\scene\scene.py", line 688, in compile_play_args_to_animation_list
    raise ValueError(
ValueError:
                    I think you may have invoked a method
                    you meant to pass in as a Scene.play argument`

#line 70 is rotate()

**Comment by behackl** [comment] 2021-01-10 12:01
The ValueError (`ValueError: I think you may have invoked a method you meant to pass in as a Scene.play argument`) already indicates the problem: in order to animate the rotation, your call

```
self.play(
            arrow.rotate(i*PI/4),
            run_time=3
        )
```

has to be written as

```
self.play(
            arrow.animate.rotate(i*PI/4),
            run_time=3
        )
```

Not a bug. Closing.

**Closed by behackl** 2021-01-10 12:01 UTC
Labels: bug

**Comment by Analytical1703** [comment] 2021-01-10 12:04
`.animate()` is also not working you fool

**Comment by behackl** [comment] 2021-01-10 12:04
... the error also indicates that you are not on the latest version of the community edition; my comment above only works with that. On older versions, you would put

```py
self.play(arrow.rotate, i*PI/4, run_time=3)
```

or so. I strongly encourage you to upgrade, though.

**Comment by Analytical1703** [comment] 2021-01-10 12:05
Tell me how to upgrade it

**Comment by behackl** [comment] 2021-01-10 12:08
You can continue to comment on closed issues, and I will continue to reply -- if you stay respectful, and calling someone a fool is really quite the opposite. Open issues are for actual bugs or enhancement proposals in the library, and not for discussing user errors.

Guessing from your install path, I'd think you used `pip install manim` at some point... then `pip install manim --upgrade` should do the trick.

**Comment by leotrs** [comment] 2021-01-10 16:58
> `.animate()` is also not working you fool

@Analytical1703 Calling names is not acceptable behavior in our community. Should you continue to have issues, feel free to keep reporting them. If you do so, DO NOT call names to those who are trying to help you. 

I'm locking this issue.
