### ISSUE TITLE
The `Contributing` docs should use `main`, not `master`

### ISSUE THREAD

**Issue by hydrobeam** [ManimCommunity/manim#1699] opened 2021-06-16 08:20 UTC
## Enhancement proposal

The [contributing docs](https://docs.manim.community/en/latest/contributing/development.html) refer to the upstream repository as `master` instead of `main`. This is incorrect and they should be changed to use the proper name.

**Comment by Darylgolden** [comment] 2021-06-16 08:49
Duplicate of #1656, closing

**Closed by Darylgolden** 2021-06-16 08:49 UTC
Labels: documentation, good first issue
