### ISSUE TITLE
Flash animation is not bound to an object on screen

### ISSUE THREAD

**Issue by sshen515** [ManimCommunity/manim#2358] opened 2021-12-03 14:53 UTC
## Description of bug / unexpected behavior

Flash is not bound on objects in 0.12.0. The flash animation seems to only occur at the origin.

## Expected behavior

The flash effect should be bound to an item on the scene.

## How to reproduce the issue
The documentation itself illustrates this issue and using `Flash` on an object that's not at the origin can also reproduce this issue.
https://docs.manim.community/en/stable/reference/manim.animation.indication.Flash.html?highlight=Flash#flash

## Additional media files

This is a screenshot of the resulting documentation example since my video is too busy visually for the purpose of this ticket. You can see the flashing effect is animated on the dot. 
![Screenshot (46)](https://user-images.githubusercontent.com/6016719/144622412-a2f3d054-8adc-40a0-93af-52ae6e122595.png)

**Comment by icedcoffeeee** [comment] 2021-12-03 15:00
Duplicate of #2257 and fixed in #2292. Closing.

**Closed by icedcoffeeee** 2021-12-03 15:00 UTC
Labels: invalid

**Comment by icedcoffeeee** [comment] 2021-12-03 15:02
you can see the latest version of the documentation for reference: https://docs.manim.community/en/latest/reference/manim.animation.indication.Flash.html
