### ISSUE TITLE
`TypeError`: set_style() got an unexpected keyword argument 'stroke_opacity'

### ISSUE THREAD

**Issue by saudzahirr** [ManimCommunity/manim#2653] opened 2022-04-04 11:08 UTC
## Description
Issue in writing Tex with background rectangle.

</br>

```py
from manim import *


class Test(Scene):
    def construct(self):
        self.camera.background_color = GREY_D
        
        text = Tex("Manim")
        text.scale(4)
        text.add_background_rectangle()

        # self.add(text)
        self.play(
            Write(text)
        )
        self.wait()
```
</br>
This is output using self.add(text):
</br>

![Test_ManimCE_v0 15 1](https://user-images.githubusercontent.com/76210541/161526057-ec7292a7-e862-4619-84b0-04038ac73054.png)

## System Environment:
```
- OS: Windows 10
- RAM: 8 GB
- Python version: Python 3.9.9
```

### LaTeX version:
```
This is pdfTeX, Version 3.141592653-2.6-1.40.23 (MiKTeX 21.8)
```

### FFmpeg version:
```
ffmpeg version 2021-03-24-git-a77beea6c8-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
libavutil      56. 72.100 / 56. 72.100
libavcodec     58.135.100 / 58.135.100
libavformat    58. 77.100 / 58. 77.100
libavdevice    58. 14.100 / 58. 14.100
libavfilter     7.111.100 /  7.111.100
libswscale      5. 10.100 /  5. 10.100
libswresample   3. 10.100 /  3. 10.100
libpostproc    55. 10.100 / 55. 10.100
```

**Comment by behackl** [comment] 2022-04-04 11:55
Hello! For the next time, please include the full stack trace with your report. This looks to be a duplicate of #1388 and should be fixed by adapting the implementation of `BackgroundRectangle.set_style` in `mobject/geometry/shape_matchers.py`.

**Closed by behackl** 2022-04-04 11:55 UTC
Labels: bug
