### ISSUE TITLE
Cached animations/updaters not working correctly...

### ISSUE THREAD

**Issue by sparshg** [ManimCommunity/manim#974] opened 2021-01-28 15:35 UTC
## Description of bug / unexpected behavior

When you run certain scene again without editing anything, the output is not the same. New partial_movie_files gets created with different names and different output...

## How to reproduce the issue
I guess the animations involving updaters get affected... Running the same scene again without editing code at all, will result in weird things. For example: [This scene](https://docs.manim.community/en/v0.2.0/examples.html#pointwithtrace) and [here](https://pastebin.com/d3X2g1Wp) is the one in which I found this issue after spending hours figuring out whats wrong...

Doing ```rm -rf media``` is a temporary workaround

## Additional media files

<details><summary>Example 1</summary>

#### First run:
![Vectors](https://user-images.githubusercontent.com/43041139/106160626-09b41c80-61ac-11eb-8b28-3bef0df96684.gif)

#### Run again without editing anything, objects teleport at origin in last second
![Vectors](https://user-images.githubusercontent.com/43041139/106160855-4aac3100-61ac-11eb-94c7-1ce5ff6a87d0.gif)

</details>

<details><summary>Example 2</summary>

#### First run:
![PointWithTrace](https://user-images.githubusercontent.com/43041139/106161040-7deec000-61ac-11eb-80d8-6cac8f1e5560.gif)

#### Run again without editing anything
![PointWithTrace](https://user-images.githubusercontent.com/43041139/106161611-39175900-61ad-11eb-865c-11305fab5049.gif)

</details>

Edit: #550

**Comment by huguesdevimeux** [comment] 2021-02-08 14:30
Sorry to not get to this back sooner. It seems that it's a duplicate of #550 (but with adding some additonal informations, which is very great!)

Therefore, I'll close it/

**Closed by huguesdevimeux** 2021-02-08 14:30 UTC
Labels: bug
