### ISSUE TITLE
Unsuccessful use of First Steps with Manim notebook

### ISSUE THREAD

**Issue by iglesias** [ManimCommunity/manim#3445] opened 2023-11-09 09:22 UTC
#### Preliminaries

- I have followed the latest version of the
      [installation instructions](https://docs.manim.community/en/stable/installation.html).
- I have checked the [installation FAQ](https://docs.manim.community/en/stable/faq/installation.html) and my problem is either not mentioned there,
      or the solution given there does not help.

## Description of error
The Notebook does not play the videos when running the first few cells one by one (Edge, Chrome, Chromium). The Notebook halts and the browser indicates it has errored (Chromium).

https://try.manim.community/

## Installation logs

<details><summary>There's no Terminal output. See for example the screenshot below</summary>

![image](https://github.com/ManimCommunity/manim/assets/1158006/69e2a79d-b739-4493-bc6f-4f121a6e8586)
</details>

## System specifications

<details><summary>System Details</summary>

- It has shown to be unusable from different browsers

## Additional comments
N/A

**Comment by uwezi** [comment] 2023-11-09 13:24
The link https://try.manim.community/ has absolutely nothing to do with your own local installation of Manim. It uses an online cloud service called Binder, which is sadly running out of resources because of a lack of commercial funding.

**Comment by behackl** [comment] 2023-11-09 19:32
Not sure I really understand what happens when you say

> The Notebook halts and the browser indicates it has errored (Chromium).

How does the notebook indicate that? Might just have been a hickup of Binder, which is out of our control. I just tried too and got a working notebook.

**Comment by iglesias** [comment] 2023-11-10 07:41
> The link https://try.manim.community/ has absolutely nothing to do with your own local installation of Manim. It uses an online cloud service called Binder, which is sadly running out of resources because of a lack of commercial funding.

Please revise your (as contributor) template for issues.
When it sadly lacks commercial funding, importantly, making it not to work, please consider making a note where the feature is advertised.

**Comment by iglesias** [comment] 2023-11-10 07:42
> Not sure I really understand what happens when you say
> 
> > The Notebook halts and the browser indicates it has errored (Chromium).
> 
> How does the notebook indicate that? Might just have been a hickup of Binder, which is out of our control. I just tried too and got a working notebook.

It is definitely not a single event (cf. listed browsers), I have been trying several days over a week.

**Comment by iglesias** [comment] 2023-11-10 07:44
Contributor/member were already aware of the issue, >350 issues open -> I assume it won't be fixed, closing.

**Comment by behackl** [comment] 2023-11-10 08:58
I don't understand yet whether it is something that is in our control of being fixed. From what I can see on your screenshot, binder seemed to have successfully spawned an instance.

@iglesias, can you please describe in more detail what happens exactly when you visit https://try.manim.community?

**Comment by iglesias** [comment] 2023-11-10 10:49
> @iglesias, can you please describe in more detail what happens exactly when you visit https://try.manim.community?

Hmm, actually, I don't think so because I don't think other details are relevant, in addition to what has been described. On the other hand, what I can do for you is put another screenshot (since I just tried again): 
![image](https://github.com/ManimCommunity/manim/assets/1158006/053e5348-a2b1-4b59-b31d-584c80841e08)
The intention must be that the video plays when pressing the play button, instead of

Can you please let me know if the new screenshot together with the short description clarify?

PS. After some seconds, scrolling down doesn't work.

**Comment by behackl** [comment] 2023-11-10 11:04
Details are very relevant: the image you are showing indicates that you do get a running instance assigned to by binder, this does not appear to be an external resource problem. This was not clear from your initial report.

Can you open your browser's development console (usually with the F12-key) and check whether there are any errors or warnings in the "Console"-tab present when the site starts to freeze?

I can't reproduce this behavior on any of my devices, this is why you will need to provide more information if you want us to try and locate a potential error on our side.

**Comment by iglesias** [comment] 2023-11-10 18:55
Thank you for the explanation.

Did you try with Chromium?

By the way, I have now started using manim locally so this is not blocking me.

**Comment by iglesias** [comment] 2023-11-10 19:14
I have tried one more time with Edge and it is working now (tried up to the and including the 5th code cell). The failure in the screenshot from today could be related to Chromium (in general or at my end).

**Comment by behackl** [comment] 2023-11-11 21:40
I have tested it with Chromium too and could not reproduce the issue either. I'm closing this for now, let us know in case you can provide more information so that we can reproduce the issue (but I suspect that this is, in the end, not a problem caused by Manim).

**Closed by behackl** 2023-11-11 21:40 UTC
Labels: installation

**Comment by iglesias** [comment] 2023-11-13 07:57
Thanks for testing it in Chromium, good that it works with it.
