### ISSUE TITLE
Make us able to use Python 3.11 for Manim

### ISSUE THREAD

**Issue by JoaoFelipe3** [ManimCommunity/manim#3240] opened 2023-05-15 18:11 UTC
## Description of proposed feature
Yeah... Seems like Manim can't run on Python 3.11. That's really disappointing. I use Python 3.11 for practically anything, but for Manim I have to switch to 3.10?

## How can the new feature be used?
So, this would be useful for being able to use the latest Python and be able to use Python 3.11's features.

**Comment by behackl** [comment] 2023-05-15 20:48
Our test suite is already run with Python 3.11 (see e.g. https://github.com/ManimCommunity/manim/actions/runs/4983964335/jobs/8921668809); Python 3.11 is already supported.

More information on what does not seem to work for you would be helpful.

**Comment by tjf801** [comment] 2023-05-16 20:37
I'm running manim on python 3.11 right now. What exactly isn't working?

**Comment by behackl** [comment] 2023-05-22 22:49
Closing as invalid / can't reproduce.

**Closed by behackl** 2023-05-22 22:49 UTC
Labels: new feature
