### ISSUE TITLE
Parameters section is duplicated in `arrange_in_grid`

### ISSUE THREAD

**Issue by hydrobeam** [ManimCommunity/manim#1443] opened 2021-05-02 17:00 UTC
## Description of bug / unexpected behavior

There are two sets of parameters listed in the docs for `arrange_in_grid`. The second copy does not have any comments.

## How to reproduce the issue

[Link to the method in the docs](https://docs.manim.community/en/latest/reference/manim.mobject.mobject.Mobject.html?highlight=arrange%20in%20grid#manim.mobject.mobject.Mobject.arrange_in_grid)

</details>

The duplicated parameters: 
![image](https://user-images.githubusercontent.com/70682032/116821017-fe271780-ab45-11eb-9015-102b81dbfd9c.png)

## Additional comments

This issue was first introduced in #1398 with the upgrades to the method.

**Comment by naveen521kk** [comment] 2021-05-04 07:41
Marking this as a "good first issue" as it is easy to fix.

**Comment by AntonBallmaier** [comment] 2021-05-04 08:16
> Marking this as a "good first issue" as it is easy to fix.

Is it? I wouldn't know how.

**Comment by hydrobeam** [comment] 2021-05-13 07:40
I also noticed this issue in #1472 under [get_t_label](https://manimce--1472.org.readthedocs.build/en/1472/reference/manim.mobject.coordinate_systems.CoordinateSystem.html#manim.mobject.coordinate_systems.CoordinateSystem.get_T_label).

I'm not sure what could be causing it 🤷‍♂️

**Comment by Lalourche** [comment] 2021-08-05 18:57
This seems caused by the order of the sections.
Fixed by moving the "Notes" section after "Raises" section. 
See PR #1869

**Closed** 2021-08-05 19:20 UTC
Labels: documentation, good first issue, bug
