### ISSUE TITLE
Brace text causes "list index out of range"

### ISSUE THREAD

**Issue by plof27** [ManimCommunity/manim#723] opened 2020-11-17 18:07 UTC
`Windows 10, Python 3.8.6, latest Manim Chocolatey`

## Description of bug / unexpected behavior
When trying to label a brace with some text, manim throws `IndexError: list index out of range`

## How to reproduce the issue

Attempting to call `get_text` on a `Brace` with any non-empty string produces the error.

<details><summary>Code for reproducing the problem</summary>

```py
class BraceAnnotation(Scene):
  def construct(self):
    dot = Dot([0, 0, 0])
    dot2 = Dot([2, 1, 0])

    line = Line(dot.get_center(), dot2.get_center()).set_color(ORANGE)
    
    b1 = Brace(line)
    b1text = b1.get_text("Distance")
    b2 = Brace(line, direction=line.copy().rotate(PI / 2).get_unit_vector())
    b2text = b2.get_tex("x-x_1")
    
    self.add(line, dot, dot2)
    self.add(b1, b2)
    self.add(b1text, b2text)
    self.wait(1)
```

</details>

The observant will notice that this is one of the examples on the documentation, [BraceAnnotation](https://docs.manim.community/en/latest/examples/annotations.html#braceannotation).

## Logs
<details><summary>Terminal output</summary>

```
PS D:\Documents\Programming\manim-test> manim annotations.py BraceAnnotation -p -qm
[11/17/20 12:01:44] INFO     Wait 0 : Using cached data (hash : 3311320791_1_2195149358)                                                                                                                       caching.py:88 
[11/17/20 12:01:45] INFO                                                                                                                                                                            scene_file_writer.py:638 
                             File ready at D:\Documents\Programming\manim-test\media\videos\annotations\720p30\BraceAnnotation.mp4

                    INFO     Rendered BraceAnnotation                                                                                                                                                            scene.py:93 
                             Played 1 animations
PS D:\Documents\Programming\manim-test> manim annotations.py BraceAnnotation -p -qm
c:\python38\lib\site-packages\manim\mobject\svg\svg_mobject.py:126: UserWarning: g0-68 not recognized
  warnings.warn("%s not recognized" % ref)
c:\python38\lib\site-packages\manim\mobject\svg\svg_mobject.py:126: UserWarning: g0-105 not recognized
  warnings.warn("%s not recognized" % ref)
c:\python38\lib\site-packages\manim\mobject\svg\svg_mobject.py:126: UserWarning: g0-115 not recognized
  warnings.warn("%s not recognized" % ref)
c:\python38\lib\site-packages\manim\mobject\svg\svg_mobject.py:126: UserWarning: g0-116 not recognized
  warnings.warn("%s not recognized" % ref)
c:\python38\lib\site-packages\manim\mobject\svg\svg_mobject.py:126: UserWarning: g0-97 not recognized
  warnings.warn("%s not recognized" % ref)
c:\python38\lib\site-packages\manim\mobject\svg\svg_mobject.py:126: UserWarning: g0-110 not recognized
  warnings.warn("%s not recognized" % ref)
c:\python38\lib\site-packages\manim\mobject\svg\svg_mobject.py:126: UserWarning: g0-99 not recognized
  warnings.warn("%s not recognized" % ref)
c:\python38\lib\site-packages\manim\mobject\svg\svg_mobject.py:126: UserWarning: g0-101 not recognized
  warnings.warn("%s not recognized" % ref)



Traceback (most recent call last):
  File "c:\python38\lib\site-packages\manim\__main__.py", line 75, in main
    scene.render()
  File "c:\python38\lib\site-packages\manim\scene\scene.py", line 88, in render
    self.construct()
  File "annotations.py", line 11, in construct
    b1text = b1.get_text("Distance")
  File "c:\python38\lib\site-packages\manim\mobject\svg\brace.py", line 61, in get_text
    text_mob = Tex(*text)
  File "c:\python38\lib\site-packages\manim\mobject\svg\tex_mobject.py", line 207, in __init__
    self.break_up_by_substrings(config)
  File "c:\python38\lib\site-packages\manim\mobject\svg\tex_mobject.py", line 244, in break_up_by_substrings
    sub_tex_mob.move_to(self.submobjects[last_submob_index], RIGHT)
IndexError: list index out of range
```

</details>

## Additional comments

This is most likely related to #469

**Comment by leotrs** [comment] 2020-11-18 00:37
Hi! Thank you for your report. The code you have shared does not contain any animations. Have you tried running this script using the `-s` flag?

**Comment by plof27** [comment] 2020-11-18 16:03
I have tried, yes, but I still get the same issue.

**Comment by leotrs** [comment] 2020-11-18 22:31
@plof27 I am led to believe that this should be working with the latest (as of today) version. Unforunately, the chocolatey package is not updated daily, so this should be fixed eventually, as soon as the current version makes its way to chocolatey. Cc @behackl @naveen521kk

**Comment by cobordism** [comment] 2020-11-28 19:12
also, which version of dvisvgm are you using here?

**Comment by jsonvillanueva** [comment] 2020-12-02 13:44
Tested on windows 10 Version 20H2 (Python 3.9) with poetry install and with a fresh install using `choco install manimce`. Both installations were able to generate the following image from the given sample scene.
![BraceAnnotation](https://user-images.githubusercontent.com/29168469/100879282-1ba16980-3460-11eb-926e-b0cb70795662.png)
Also was able to generate the mp4. This seems to be an installation issue and not a bug with manim.

**Comment by leotrs** [comment] 2020-12-02 13:59
I can confirm this (the manim part at least) should be fixed on master (and eventually/already on chocolatey).

@plof27 perhaps try with a fresh install? Or try the dockerfile. If you continue having problems with installation, please open another issue, or ping us on our Discord server :slightly_smiling_face:

**Closed by leotrs** 2020-12-02 13:59 UTC
Labels: bug

**Comment by cobordism** [comment] 2020-12-02 14:01
can you try once more with `config["tex_template"] = TexTemplateLibrary.simple` at the top of the scene?

**Comment by wengjianfeng** [comment] 2021-04-10 02:27
> can you try once more with `config["tex_template"] = TexTemplateLibrary.simple` at the top of the scene?

It works, thanks very much! But would you pls explain why this method works?

**Comment by cobordism** [comment] 2021-04-10 09:34
> But would you pls explain why this method works?

The default tex template loads a lot of tex packages. I don't know exactly which combination of loaded packages combined with which version of dvisvgm causes the error, but I do know that 99% of the time, all you need is the simple template and that this fixes the issue of "g0-116 not recognized". To investigate further, you'd have to systematically alter the tex templates and see what is causing the error.

The simple template starts with:
```
\documentclass[preview]{standalone}
\usepackage[english]{babel}
\usepackage{amsmath}
\usepackage{amssymb}
```
While the default one was inherited from upstream 3b1b with:
```
\documentclass[preview]{standalone}
\usepackage[english]{babel}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{dsfont}
\usepackage{setspace}
\usepackage{tipa}
\usepackage{relsize}
\usepackage{textcomp}
\usepackage{mathrsfs}
\usepackage{calligra}
\usepackage{wasysym}
\usepackage{ragged2e}
\usepackage{physics}
\usepackage{xcolor}
\usepackage{microtype}
\DisableLigatures{encoding = *, family = * }
\linespread{1}
```

Important thing to note: When you change the templates directly without changing the code in your Scene, you have to manually delete the `media` directory before you try rendering again, otherwise the old tex will be reused. Even manim's `--disable_cache` (or whatever the cache command is) will not clear out the tex cache.

**Comment by behackl** [comment] 2021-04-10 11:32
The issue usually comes from using `\usepackage[T1]{fontenc}` while not having the `cm-super` LaTeX package installed. Assuming you have installed LaTeX via MiKTeX, you can open the MiKTeX console, install `cm-super`, and `Tex` will start to work for you even without using the simple template.

There is a more detailed discussion about this over at https://github.com/3b1b/manim/issues/1276 in case you are interested in all the gory details.

**Comment by algasami** [comment] 2022-12-28 07:00
@behackl Sorry for bumping this thread, but it appears that `cm-super` has no effect on my error. I have double-checked my installation and the package has been installed. The error still persists. I believe it is `==` that causes the issue in my environment, because other snippets without this symbol work perfectly fine.
```python
functionCode = Code(
    code=r"""
    int parent[MAX_SIZE];
    int findRoot(int x) {
        if (x == parent[x]) return x;
        return findRoot(parent[x]);
    }
    """,
    tab_width=4,
    background="window",
    font="Fira Code",
    language="cpp",
)
```
Here is my code snippet.
