### ISSUE TITLE
FadeOut uses wrong cache for ImageMobject

### ISSUE THREAD

**Issue by aRySt0cat** [ManimCommunity/manim#3068] opened 2022-12-09 05:23 UTC
## Description of bug / unexpected behavior

Repeated FadeIn and FadeOut of multiple ImageMobjects seems to cause FadeOut to use the wrong cache.
When the attached code was executed with the following command, the animation of the first FadeOut was played during the second FadeOut.
```sh
manim -pql <script>
```
On the other hand, the following command produces the correct animation
```sh
manim -pql --disable_caching <script>
```
## Expected behavior

The same behavior regardless of whether the cache is enabled or disabled

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
from manim import *


class FadeOutImage(Scene):
    def construct(self):
        data1 = np.zeros((100, 100))
        data1[:, 0:5] = 255
        data1[0:5, :] = 255
        data1[:, -6:-1] = 255
        data1[-6:-1, :] = 255
        data2 = np.zeros((100, 100))
        data2[:, 25:30] = 255
        data2[25:30, :] = 255
        data2[:, -31:-26] = 255
        data2[-31:-26, :] = 255
        data = [data1, data2]
        for i in range(2):
            image = ImageMobject(data[i])
            self.play(FadeIn(image))
            self.play(FadeOut(image))

```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

![cache_enabled](https://user-images.githubusercontent.com/55921454/206629584-ad4712d0-9e38-4c6d-b844-49ac55660715.gif)
![cache_disabled](https://user-images.githubusercontent.com/55921454/206629609-26996234-a53a-4908-8f17-b801ce7526fa.gif)

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)): macOS 13.0 (Ventura)
- RAM: 
- Python version (`python/py/python3 --version`): 3.8.15
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
ffmpeg version 5.1.2 Copyright (c) 2000-2022 the FFmpeg developers
built with Apple clang version 14.0.0 (clang-1400.0.29.102)
configuration: --prefix=/usr/local/Cellar/ffmpeg/5.1.2 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
```
</details>

**Comment by huguesdevimeux** [comment] 2022-12-09 17:14
Hello and thanks for the report !

I think this is a duplicate of #2924

**Closed by huguesdevimeux** 2022-12-09 17:14 UTC
