### ISSUE TITLE
MissingFunctionException

### ISSUE THREAD

**Issue by claroja** [ManimCommunity/manim#3000] opened 2022-10-25 01:03 UTC
## Description of bug / unexpected behavior
I got MissingFunctionException when runing manim

## How to reproduce the issue

<details><summary>MissingFunctionException</summary>

```py
from manim import *

class CreateCircle(Scene):
    def construct(self):
        circle = Circle()  # create a circle
        circle.set_fill(PINK, opacity=0.5)  # set the color and transparency
        self.play(Create(circle))  # show the circle on screen
```
then I ran this command:
```sh
manim -pql scene.py CreateCircle --renderer opengl
```

</details>

## Logs
<details><summary>Terminal output</summary>

```
Manim Community v0.16.0.post0

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\Program Files\Python310\lib\site-packages\manim\cli\render\commands.py:102 in render          │
│                                                                                                  │
│    99 │   │   │   while keep_running:                                                            │
│   100 │   │   │   │   for SceneClass in scene_classes_from_file(file):                           │
│   101 │   │   │   │   │   with tempconfig(config):                                               │
│ ❱ 102 │   │   │   │   │   │   scene = SceneClass(renderer)                                       │
│   103 │   │   │   │   │   │   rerun = scene.render()                                             │
│   104 │   │   │   │   │   if rerun or config["write_all"]:                                       │
│   105 │   │   │   │   │   │   renderer.num_plays = 0                                             │
│                                                                                                  │
│ D:\Program Files\Python310\lib\site-packages\manim\scene\scene.py:140 in __init__                │
│                                                                                                  │
│    137 │   │   │   )                                                                             │
│    138 │   │   else:                                                                             │
│    139 │   │   │   self.renderer = renderer                                                      │
│ ❱  140 │   │   self.renderer.init_scene(self)                                                    │
│    141 │   │                                                                                     │
│    142 │   │   self.mobjects = []                                                                │
│    143 │   │   # TODO, remove need for foreground mobjects                                       │
│                                                                                                  │
│ D:\Program Files\Python310\lib\site-packages\manim\renderer\opengl_renderer.py:263 in init_scene │
│                                                                                                  │
│   260 │   │   │   if self.should_create_window():                                                │
│   261 │   │   │   │   from .opengl_renderer_window import Window                                 │
│   262 │   │   │   │                                                                              │
│ ❱ 263 │   │   │   │   self.window = Window(self)                                                 │
│   264 │   │   │   │   self.context = self.window.ctx                                             │
│   265 │   │   │   │   self.frame_buffer_object = self.context.detect_framebuffer()               │
│   266 │   │   │   else:                                                                          │
│                                                                                                  │
│ D:\Program Files\Python310\lib\site-packages\manim\renderer\opengl_renderer_window.py:39 in      │
│ __init__                                                                                         │
│                                                                                                  │
│    36 │   │   else:                                                                              │
│    37 │   │   │   size = tuple(size)                                                             │
│    38 │   │                                                                                      │
│ ❱  39 │   │   super().__init__(size=size)                                                        │
│    40 │   │                                                                                      │
│    41 │   │   self.title = f"Manim Community {__version__}"                                      │
│    42 │   │   self.size = size                                                                   │
│                                                                                                  │
│ D:\Program Files\Python310\lib\site-packages\moderngl_window\context\pyglet\window.py:51 in      │
│ __init__                                                                                         │
│                                                                                                  │
│    48 │   │   │   screen = display.get_default_screen()                                          │
│    49 │   │   │   self._width, self._height = screen.width, screen.height                        │
│    50 │   │                                                                                      │
│ ❱  51 │   │   self._window = PygletWrapper(                                                      │
│    52 │   │   │   width=self._width,                                                             │
│    53 │   │   │   height=self._height,                                                           │
│    54 │   │   │   caption=self._title,                                                           │
│                                                                                                  │
│ D:\Program Files\Python310\lib\site-packages\pyglet\window\win32\__init__.py:138 in __init__     │
│                                                                                                  │
│    135 │   │   self._always_dwm = sys.getwindowsversion() >= (6, 2)                              │
│    136 │   │   self._interval = 0                                                                │
│    137 │   │                                                                                     │
│ ❱  138 │   │   super(Win32Window, self).__init__(*args, **kwargs)                                │
│    139 │                                                                                         │
│    140 │   def _recreate(self, changes):                                                         │
│    141 │   │   if 'context' in changes:                                                          │
│                                                                                                  │
│ D:\Program Files\Python310\lib\site-packages\pyglet\window\__init__.py:617 in __init__           │
│                                                                                                  │
│    614 │   │                                                                                     │
│    615 │   │   self.switch_to()                                                                  │
│    616 │   │                                                                                     │
│ ❱  617 │   │   self._create_projection()                                                         │
│    618 │   │                                                                                     │
│    619 │   │   if visible:                                                                       │
│    620 │   │   │   self.set_visible(True)                                                        │
│                                                                                                  │
│ D:\Program Files\Python310\lib\site-packages\pyglet\window\__init__.py:625 in _create_projection │
│                                                                                                  │
│    622 │                                                                                         │
│    623 │   def _create_projection(self):                                                         │
│    624 │   │   self._default_program = shader.ShaderProgram(                                     │
│ ❱  625 │   │   │   shader.Shader(self._default_vertex_source, 'vertex'),                         │
│    626 │   │   │   shader.Shader(self._default_fragment_source, 'fragment'))                     │
│    627 │   │                                                                                     │
│    628 │   │   self.ubo = self._default_program.uniform_blocks['WindowBlock'].create_ubo()       │
│                                                                                                  │
│ D:\Program Files\Python310\lib\site-packages\pyglet\graphics\shader.py:259 in __init__           │
│                                                                                                  │
│   256 │   │   source_buffer_pointer = cast(c_char_p(shader_source_utf8), POINTER(c_char))        │
│   257 │   │   source_length = c_int(len(shader_source_utf8))                                     │
│   258 │   │                                                                                      │
│ ❱ 259 │   │   shader_id = glCreateShader(_shader_types[shader_type])                             │
│   260 │   │   glShaderSource(shader_id, 1, byref(source_buffer_pointer), source_length)          │
│   261 │   │   glCompileShader(shader_id)                                                         │
│   262                                                                                            │
│                                                                                                  │
│ D:\Program Files\Python310\lib\site-packages\pyglet\gl\lib_wgl.py:101 in __call__                │
│                                                                                                  │
│    98 │   │                                                                                      │
│    99 │   │   self.__class__ = makeWGLFunction(self.func)                                        │
│   100 │   │                                                                                      │
│ ❱ 101 │   │   return self.func(*args, **kwargs)                                                  │
│   102                                                                                            │
│   103                                                                                            │
│   104 def link_GL(name, restype, argtypes, requires=None, suggestions=None):                     │
│                                                                                                  │
│ D:\Program Files\Python310\lib\site-packages\pyglet\gl\lib.py:60 in MissingFunction              │
│                                                                                                  │
│    57                                                                                            │
│    58 def missing_function(name, requires=None, suggestions=None):                               │
│    59 │   def MissingFunction(*args, **kwargs):                                                  │
│ ❱  60 │   │   raise MissingFunctionException(name, requires, suggestions)                        │
│    61 │                                                                                          │
│    62 │   return MissingFunction                                                                 │
│    63                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
MissingFunctionException: glCreateShader is not exported by the available OpenGL driver.  OpenGL 2.0 is required for this functionality.
```

</details>

## System specifications

<details><summary>System Details</summary>

```
- Python 3.10.7
- CPU Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz   2.89 GH
- manim  0.16.0.post0
```
</details>

**Comment by behackl** [comment] 2022-10-25 16:41
It looks like your device doesn't support rendering with OpenGL; the error is thrown when importing `pyglet` and not within Manim itself, perhaps the people over at [pyglet](https://github.com/pyglet/pyglet) can help you.

Closing this, as it is not a bug with Manim.

**Closed by behackl** 2022-10-25 16:41 UTC
