### ISSUE TITLE
Error rendering Text mobject on certain Macs - Argument 'size' has incorrect type (expected int, got float)

### ISSUE THREAD

**Issue by haochenuw** [ManimCommunity/manim#3442] opened 2023-11-05 18:15 UTC
## Description of bug / unexpected behavior
Error rendering Text mobject on certain Mac models. 

## Expected behavior
Can render a text mobject

## How to reproduce the issue

Install manim using conda. 

<details><summary>Code for reproducing the problem</summary>

```py
        t = Text("abc")
        self.add(t) 
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

(manim-venv) haoche-mp:manim-project1 haoche$ manim -ql scene.py 
Manim Community v0.17.3

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/haoche/opt/anaconda3/envs/manim-venv/lib/python3.11/site-packages/manim/cli/render/comman │
│ ds.py:115 in render                                                                              │
│                                                                                                  │
│   112 │   │   │   try:                                                                           │
│   113 │   │   │   │   with tempconfig({}):                                                       │
│   114 │   │   │   │   │   scene = SceneClass()                                                   │
│ ❱ 115 │   │   │   │   │   scene.render()                                                         │
│   116 │   │   │   except Exception:                                                              │
│   117 │   │   │   │   error_console.print_exception()                                            │
│   118 │   │   │   │   sys.exit(1)                                                                │
│                                                                                                  │
│ /Users/haoche/opt/anaconda3/envs/manim-venv/lib/python3.11/site-packages/manim/scene/scene.py:22 │
│ 3 in render                                                                                      │
│                                                                                                  │
│    220 │   │   """                                                                               │
│    221 │   │   self.setup()                                                                      │
│    222 │   │   try:                                                                              │
│ ❱  223 │   │   │   self.construct()                                                              │
│    224 │   │   except EndSceneEarlyException:                                                    │
│    225 │   │   │   pass                                                                          │
│    226 │   │   except RerunSceneException as e:                                                  │
│                                                                                                  │
│ /Users/haoche/Repos/manim-project1/scene.py:47 in construct                                      │
│                                                                                                  │
│   44 │   │                                                                                       │
│   45 │   │   polygon = always_redraw(get_rectangle)                                              │
│   46 │   │                                                                                       │
│ ❱ 47 │   │   t = Text("abc")                                                                     │
│   48 │   │                                                                                       │
│   49 │   │   # dot = Dot()                                                                       │
│   50 │   │   # dot.add_updater(lambda x: x.move_to(ax.c2p(t.get_value(), k / t.get_value())))    │
│                                                                                                  │
│ /Users/haoche/opt/anaconda3/envs/manim-venv/lib/python3.11/site-packages/manim/mobject/text/text │
│ _mobject.py:486 in __init__                                                                      │
│                                                                                                  │
│    483 │   │   │   self.line_spacing = self._font_size + self._font_size * self.line_spacing     │
│    484 │   │                                                                                     │
│    485 │   │   color = Color(color) if color else VMobject().color                               │
│ ❱  486 │   │   file_name = self._text2svg(color)                                                 │
│    487 │   │   PangoUtils.remove_last_M(file_name)                                               │
│    488 │   │   super().__init__(                                                                 │
│    489 │   │   │   file_name,                                                                    │
│                                                                                                  │
│ /Users/haoche/opt/anaconda3/envs/manim-venv/lib/python3.11/site-packages/manim/mobject/text/text │
│ _mobject.py:814 in _text2svg                                                                     │
│                                                                                                  │
│    811 │   │   │   width = config["pixel_width"]                                                 │
│    812 │   │   │   height = config["pixel_height"]                                               │
│    813 │   │   │                                                                                 │
│ ❱  814 │   │   │   svg_file = manimpango.text2svg(                                               │
│    815 │   │   │   │   settings,                                                                 │
│    816 │   │   │   │   size,                                                                     │
│    817 │   │   │   │   line_spacing,                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: Argument 'size' has incorrect type (expected int, got float)

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
Mac Pro 2019
OS: macOS 14.0 
RAM: 96GB

Python 3.8.9


(manim-venv) haoche-mp:manim-project1 haoche$ pip list
Package                                           Version
------------------------------------------------- -----------
azure-cognitiveservices-speech                    1.32.1
Brotli                                            1.1.0
build                                             1.0.3
CacheControl                                      0.13.1
certifi                                           2023.7.22
cffi                                              1.16.0
charset-normalizer                                3.3.2
cleo                                              2.1.0
click                                             8.1.7
click-default-group                               1.2.4
cloup                                             0.13.1
colorama                                          0.4.6
colour                                            0.1.5
crashtest                                         0.4.1
Cython                                            3.0.5
dataclasses                                       0.8
decorator                                         5.1.1
deepl                                             1.16.0
distlib                                           0.3.7
dulwich                                           0.21.6
fastjsonschema                                    2.18.1
ffmpeg-python                                     0.2.0
filelock                                          3.13.1
fsspec                                            2023.10.0
future                                            0.18.3
glcontext                                         2.5.0
gTTS                                              2.4.0
huggingface-hub                                   0.17.3
idna                                              3.4
importlib-metadata                                6.8.0
installer                                         0.7.0
isosurfaces                                       0.1.0
jaraco.classes                                    3.3.0
Jinja2                                            3.1.2
keyring                                           24.2.0
llvmlite                                          0.41.1
manim                                             0.17.3
manim-voiceover                                   0.3.4.post1
ManimPango                                        0.4.4
mapbox-earcut                                     1.0.1
markdown-it-py                                    3.0.0
MarkupSafe                                        2.1.3
mdurl                                             0.1.0
moderngl                                          5.8.2
moderngl-window                                   2.4.1
more-itertools                                    10.1.0
mpmath                                            1.3.0
msgpack                                           1.0.6
multipledispatch                                  0.6.0
mutagen                                           1.47.0
networkx                                          2.8.8
numba                                             0.58.1
numpy                                             1.26.0
openai-whisper                                    20230314
packaging                                         23.2
pexpect                                           4.8.0
Pillow                                            9.5.0
pip                                               23.3.1
pkginfo                                           1.9.6
platformdirs                                      3.11.0
poetry                                            1.7.0
poetry-core                                       1.8.1
poetry-plugin-export                              1.6.0
ptyprocess                                        0.7.0
PyAudio                                           0.2.13
pycairo                                           1.25.1
pycparser                                         2.21
pydub                                             0.25.1
pyglet                                            1.5.27
Pygments                                          2.16.1
pynput                                            1.7.6
pyobjc                                            10.0
pyobjc-core                                       10.0
pyobjc-framework-Accessibility                    10.0
pyobjc-framework-Accounts                         10.0
pyobjc-framework-AddressBook                      10.0
pyobjc-framework-AdServices                       10.0
pyobjc-framework-AdSupport                        10.0
pyobjc-framework-AppleScriptKit                   10.0
pyobjc-framework-AppleScriptObjC                  10.0
pyobjc-framework-ApplicationServices              10.0
pyobjc-framework-AppTrackingTransparency          10.0
pyobjc-framework-AudioVideoBridging               10.0
pyobjc-framework-AuthenticationServices           10.0
pyobjc-framework-AutomaticAssessmentConfiguration 10.0
pyobjc-framework-Automator                        10.0
pyobjc-framework-AVFoundation                     10.0
pyobjc-framework-AVKit                            10.0
pyobjc-framework-AVRouting                        10.0
pyobjc-framework-BackgroundAssets                 10.0
pyobjc-framework-BusinessChat                     10.0
pyobjc-framework-CalendarStore                    10.0
pyobjc-framework-CallKit                          10.0
pyobjc-framework-CFNetwork                        10.0
pyobjc-framework-Cinematic                        10.0
pyobjc-framework-ClassKit                         10.0
pyobjc-framework-CloudKit                         10.0
pyobjc-framework-Cocoa                            10.0
pyobjc-framework-Collaboration                    10.0
pyobjc-framework-ColorSync                        10.0
pyobjc-framework-Contacts                         10.0
pyobjc-framework-ContactsUI                       10.0
pyobjc-framework-CoreAudio                        10.0
pyobjc-framework-CoreAudioKit                     10.0
pyobjc-framework-CoreBluetooth                    10.0
pyobjc-framework-CoreData                         10.0
pyobjc-framework-CoreHaptics                      10.0
pyobjc-framework-CoreLocation                     10.0
pyobjc-framework-CoreMedia                        10.0
pyobjc-framework-CoreMediaIO                      10.0
pyobjc-framework-CoreMIDI                         10.0
pyobjc-framework-CoreML                           10.0
pyobjc-framework-CoreMotion                       10.0
pyobjc-framework-CoreServices                     10.0
pyobjc-framework-CoreSpotlight                    10.0
pyobjc-framework-CoreText                         10.0
pyobjc-framework-CoreWLAN                         10.0
pyobjc-framework-CryptoTokenKit                   10.0
pyobjc-framework-DataDetection                    10.0
pyobjc-framework-DeviceCheck                      10.0
pyobjc-framework-DictionaryServices               10.0
pyobjc-framework-DiscRecording                    10.0
pyobjc-framework-DiscRecordingUI                  10.0
pyobjc-framework-DiskArbitration                  10.0
pyobjc-framework-DVDPlayback                      10.0
pyobjc-framework-EventKit                         10.0
pyobjc-framework-ExceptionHandling                10.0
pyobjc-framework-ExecutionPolicy                  10.0
pyobjc-framework-ExtensionKit                     10.0
pyobjc-framework-ExternalAccessory                10.0
pyobjc-framework-FileProvider                     10.0
pyobjc-framework-FileProviderUI                   10.0
pyobjc-framework-FinderSync                       10.0
pyobjc-framework-FSEvents                         10.0
pyobjc-framework-GameCenter                       10.0
pyobjc-framework-GameController                   10.0
pyobjc-framework-GameKit                          10.0
pyobjc-framework-GameplayKit                      10.0
pyobjc-framework-HealthKit                        10.0
pyobjc-framework-ImageCaptureCore                 10.0
pyobjc-framework-InputMethodKit                   10.0
pyobjc-framework-InstallerPlugins                 10.0
pyobjc-framework-InstantMessage                   10.0
pyobjc-framework-Intents                          10.0
pyobjc-framework-IntentsUI                        10.0
pyobjc-framework-IOBluetooth                      10.0
pyobjc-framework-IOBluetoothUI                    10.0
pyobjc-framework-IOSurface                        10.0
pyobjc-framework-iTunesLibrary                    10.0
pyobjc-framework-KernelManagement                 10.0
pyobjc-framework-LatentSemanticMapping            10.0
pyobjc-framework-LaunchServices                   10.0
pyobjc-framework-libdispatch                      10.0
pyobjc-framework-libxpc                           10.0
pyobjc-framework-LinkPresentation                 10.0
pyobjc-framework-LocalAuthentication              10.0
pyobjc-framework-LocalAuthenticationEmbeddedUI    10.0
pyobjc-framework-MailKit                          10.0
pyobjc-framework-MapKit                           10.0
pyobjc-framework-MediaAccessibility               10.0
pyobjc-framework-MediaLibrary                     10.0
pyobjc-framework-MediaPlayer                      10.0
pyobjc-framework-MediaToolbox                     10.0
pyobjc-framework-Metal                            10.0
pyobjc-framework-MetalFX                          10.0
pyobjc-framework-MetalKit                         10.0
pyobjc-framework-MetalPerformanceShaders          10.0
pyobjc-framework-MetalPerformanceShadersGraph     10.0
pyobjc-framework-MetricKit                        10.0
pyobjc-framework-MLCompute                        10.0
pyobjc-framework-ModelIO                          10.0
pyobjc-framework-MultipeerConnectivity            10.0
pyobjc-framework-NaturalLanguage                  10.0
pyobjc-framework-NetFS                            10.0
pyobjc-framework-Network                          10.0
pyobjc-framework-NetworkExtension                 10.0
pyobjc-framework-NotificationCenter               10.0
pyobjc-framework-OpenDirectory                    10.0
pyobjc-framework-OSAKit                           10.0
pyobjc-framework-OSLog                            10.0
pyobjc-framework-PassKit                          10.0
pyobjc-framework-PencilKit                        10.0
pyobjc-framework-PHASE                            10.0
pyobjc-framework-Photos                           10.0
pyobjc-framework-PhotosUI                         10.0
pyobjc-framework-PreferencePanes                  10.0
pyobjc-framework-PushKit                          10.0
pyobjc-framework-Quartz                           10.0
pyobjc-framework-QuickLookThumbnailing            10.0
pyobjc-framework-ReplayKit                        10.0
pyobjc-framework-SafariServices                   10.0
pyobjc-framework-SafetyKit                        10.0
pyobjc-framework-SceneKit                         10.0
pyobjc-framework-ScreenCaptureKit                 10.0
pyobjc-framework-ScreenSaver                      10.0
pyobjc-framework-ScreenTime                       10.0
pyobjc-framework-ScriptingBridge                  10.0
pyobjc-framework-SearchKit                        10.0
pyobjc-framework-Security                         10.0
pyobjc-framework-SecurityFoundation               10.0
pyobjc-framework-SecurityInterface                10.0
pyobjc-framework-SensitiveContentAnalysis         10.0
pyobjc-framework-ServiceManagement                10.0
pyobjc-framework-SharedWithYou                    10.0
pyobjc-framework-SharedWithYouCore                10.0
pyobjc-framework-ShazamKit                        10.0
pyobjc-framework-Social                           10.0
pyobjc-framework-SoundAnalysis                    10.0
pyobjc-framework-Speech                           10.0
pyobjc-framework-SpriteKit                        10.0
pyobjc-framework-StoreKit                         10.0
pyobjc-framework-Symbols                          10.0
pyobjc-framework-SyncServices                     10.0
pyobjc-framework-SystemConfiguration              10.0
pyobjc-framework-SystemExtensions                 10.0
pyobjc-framework-ThreadNetwork                    10.0
pyobjc-framework-UniformTypeIdentifiers           10.0
pyobjc-framework-UserNotifications                10.0
pyobjc-framework-UserNotificationsUI              10.0
pyobjc-framework-VideoSubscriberAccount           10.0
pyobjc-framework-VideoToolbox                     10.0
pyobjc-framework-Virtualization                   10.0
pyobjc-framework-Vision                           10.0
pyobjc-framework-WebKit                           10.0
pyproject_hooks                                   1.0.0
pyrr                                              0.10.3
PySocks                                           1.7.1
python-dotenv                                     0.21.1
python-slugify                                    8.0.1
pyttsx3                                           2.90
PyYAML                                            6.0.1
rapidfuzz                                         3.5.2
regex                                             2023.10.3
requests                                          2.31.0
requests-toolbelt                                 1.0.0
rich                                              13.6.0
safetensors                                       0.4.0
scipy                                             1.11.3
screeninfo                                        0.8.1
setuptools                                        68.2.2
shellingham                                       1.5.4
six                                               1.16.0
skia-pathops                                      0.7.4
sox                                               1.4.1
srt                                               3.5.3
stable-ts                                         2.11.1
svgelements                                       1.9.6
sympy                                             1.12
text-unidecode                                    1.3
tiktoken                                          0.3.1
tokenizers                                        0.14.1
tomli                                             2.0.1
tomlkit                                           0.12.2
torch                                             2.1.0
torchaudio                                        2.1.0
tqdm                                              4.66.1
transformers                                      4.35.0
trove-classifiers                                 2023.10.18
typing_extensions                                 4.8.0
urllib3                                           2.0.7
virtualenv                                        20.24.6
watchdog                                          2.3.1
wheel                                             0.41.3
xattr                                             0.10.1
zipp                                              3.17.0
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by behackl** [comment] 2023-11-05 18:19
Duplicate of https://github.com/ManimCommunity/manim/issues/3403, running pip install -U --force manimpango should fix the issue. Will also be fixed with the upcoming release.

**Closed by behackl** 2023-11-05 18:19 UTC

**Comment by haochenuw** [comment] 2023-11-05 21:50
I tried that and it complains about 
```
manim 0.17.3 requires manimpango<0.5.0,>=0.4.0.post0, but you have manimpango 0.5.0 which is incompatible.
```
Then I tried `pip install -U --force manimpango==0.4.4`, then the manim command fails with 
```
AttributeError: Text object has no attribute 'value'
```
