### ISSUE TITLE
Updater won't work within defined Animation

### ISSUE THREAD

**Issue by DeclK** [ManimCommunity/manim#3063] opened 2022-12-08 12:00 UTC
## Description of bug / unexpected behavior
I noticed this bug, when I'm trying the example [**CountingScene**](https://docs.manim.community/en/stable/tutorials/building_blocks.html#countingscene), and I have commented at [request](https://github.com/ManimCommunity/manim/pull/1739). Here is the content

I have some issues about this CountingScene. I try to change the updater shown below

```python
class CountingScene(Scene):
    def construct(self):
        ....
        # number.add_updater(lambda number: number.move_to(ORIGIN))
        number.add_updater(lambda number: number.move_to(LEFT * 5))
```
In fact, this DecimalNumber won't change its position with this updater.
So I think this line of code might not be taking effects. As matter of fact, you can see in the official pages, the DecimalNumber is NOT always in the origin!

## Expected behavior
Updater should work in the defined animation

## How to reproduce the issue
Just run the code [**CountingScene**](https://docs.manim.community/en/stable/tutorials/building_blocks.html#countingscene)

## How to solve

It is caused by the function `Animation.get_all_mobjects_to_update`
```python
    def get_all_mobjects_to_update(self) -> list[Mobject]:
        """Get all mobjects to be updated during the animation.
        """
        # The surrounding scene typically handles
        # updating of self.mobject.  Besides, in
        # most cases its updating is suspended anyway
        return list(filter(lambda m: m is not self.mobject, self.get_all_mobjects()))
```
**Because the `filter` will return a new object instead of the object itself!**

**Comment by DeclK** [comment] 2022-12-08 12:20
Infact, I changed the `Animation.get_all_mobjects_to_update` still won't solve the problem...
So it must be a deeper bug😂

**Comment by DeclK** [comment] 2022-12-08 14:05
I have figured out a way to fix this issue, but I **DON'T** understand the process at all!
just resume_updating in `Scene.update_to_time` would be fine!!!
```python
    def update_to_time(self, t):
        dt = t - self.last_t
        self.last_t = t
        for animation in self.animations:
            animation.update_mobjects(dt)
            alpha = t / animation.run_time
            animation.interpolate(alpha)
            animation.mobject.resume_updating()
        self.update_mobjects(dt)
        self.update_meshes(dt)
        self.update_self(dt)
```

Looking forward to a more professional solution😀

**Comment by huguesdevimeux** [comment] 2022-12-08 19:15
Hello and thank you for the report ! 

> Because the filter will return a new object instead of the object itself!

In the general case, `filter` does not alter the objects. I don't think this is the right path to the issue.

Speaking of your issue, it looks like a very interesting corner case. Here is an MRE : 
```python

class Count(Animation):
    def __init__(
        self, number: DecimalNumber, start: float, end: float, **kwargs
    ) -> None:
        # Pass number as the mobject of the animation
        super().__init__(number, **kwargs)
        # Set start and end
        self.start = start
        self.end = end

    def interpolate_mobject(self, alpha: float) -> None:
        # self.mobject.updating_suspended = False # HERE IS A FIX
        # Set value of DecimalNumber according to alpha
        value = self.start + (alpha * (self.end - self.start))
        self.mobject.set_value(value)


class CountingScene(Scene):
    def construct(self):
        # Create Decimal Number and add it to scene
        number = DecimalNumber().set_color(WHITE).scale(5)
        def update(mb, dt):
            mb.shift(UP / 10)
        number.add_updater(update)
        self.add(number)
        self.wait()
        # Play the Count Animation to count from 0 to 100 in 4 seconds
        self.play(Count(number, 0, 100), run_time=4, rate_func=linear)
        self.wait()
```
And the following result : 

https://user-images.githubusercontent.com/36239975/206544667-f1146c74-390b-442d-ada9-e72c20dc9f91.mp4

After some little digging, it looks like **updater called are blocked during the `Count` animation.** The fix you proposed is a solution because `resume_updating` force call any updaters attached to the mobject. 

It appears that `mobject.updating_suspended` is **wrongly set to True** during the animation, thus preventing the mobject from being updated. I cannot look into the details right now, but I'm pretty sure the problem is easy to pinpoint. 

 As a "cleaner" solution (but far from clean) you can add `self.updating_suspended = False` (see the code above). 

It looks to me like an easy fix, or at least a non overly complex issue.

**Comment by huguesdevimeux** [comment] 2022-12-09 17:11
Hello again,

After a very quick dig I found out the source of the issue : 
It's actually a desired effect. Animation has an attribute `suspend_mobject_updating` that is self-explanatory, by default set to True. 

However, note that the behaviour of this attribute is broken, for example, 
```python
    def construct(self):
        s = Square()
        s.add_updater(lambda m: m.shift(UP / 10))
        self.play(Create(s))
```
will run the updater at every frame, despire `Create` having `suspend_mobject_updating` to `True`. 

The source of this wrong behaviour is here : 
```python
        self.starting_mobject = self.create_starting_mobject()
        if self.suspend_mobject_updating:
            # All calls to self.mobject's internal updaters
            # during the animation, either from this Animation
            # or from the surrounding scene, should do nothing.
            # It is, however, okay and desirable to call
            # the internal updaters of self.starting_mobject,
            # or any others among self.get_all_mobjects()
            self.mobject.suspend_updating()
```

As the comment said (the comment dates back to Grand Sanderson, 4 years ago) it is supposed to be a "desirable effect".

**Comment by huguesdevimeux** [comment] 2022-12-09 17:14
I'm closing it for now. Please feel free to reopen if you want to discuss it further.

**Closed by huguesdevimeux** 2022-12-09 17:14 UTC
Labels: issue:bug
