### ISSUE TITLE
Use of a 'toy' function for pycairo fonts

### ISSUE THREAD

**Issue by MysaaJava** [ManimCommunity/manim#470] opened 2020-09-23 05:54 UTC
I've searched how manim fonts were - loaded and i found the line https://github.com/ManimCommunity/manim/blob/faaeb89af98ed03160f44625907a3c231abbd84e/manim/mobject/svg/text_mobject.py#L314 . So i looked at pycairo documentation in order to understand how are fonts parsed and the doc tells that the function should not be used for production, only for "playing around" with cairo.
```
Note: The select_font_face() function call is part of what the cairo designers call the “toy” text API. It is convenient for short demos and simple programs, but it is not expected to be adequate for serious text-using applications.
``` on https://cairographics.org/documentation/pycairo/2/reference/context.html

I will try to work on it after school if you let me do so.

**Comment by huguesdevimeux** [comment] 2020-09-23 06:23
I think this has been said in #262 .
Unfortunately, as far as I know, there is no way to go around this limitation except by using an external library such as Pango, as mentionnée in the docs. 

This is definitely something we should do.

**Comment by naveen521kk** [comment] 2020-09-23 08:49
Duplicate of #393

**Comment by leotrs** [comment] 2020-09-23 11:30
Thanks @MysaaJava, let's continue discussion in #393

**Closed** 2020-09-23 11:29 UTC
