### ISSUE TITLE
Problem: pip3 does not point to the correct Python installation on your system.

### ISSUE THREAD

**Issue by TanrebCS** [ManimCommunity/manim#2996] opened 2022-10-17 20:51 UTC
#### Preliminaries

- [x] I have followed the latest version of the
      [installation instructions](https://docs.manim.community/en/stable/installation.html).
- [x] I have checked the [troubleshooting page](https://docs.manim.community/en/stable/installation/troubleshooting.html) and my problem is either not mentioned there,
      or the solution given there does not help.

## Description of error
I have an error (detailed by the webpage), but I don't know how to solve it. "A frequent source for installation problems is if pip3 does not point to the correct Python installation on your system. To check this, run pip3 -V: for MacOS Intel, the path should start with /usr/local, and for Apple Silicon with /opt/homebrew. If this is not the case, you either forgot to modify your shell profile (.zprofile) during the installation of Homebrew, or did not reload your shell (e.g., by opening a new terminal) after doing so. It is also possible that some other software (like Pycharm) changed the PATH variable – to fix this, make sure that the Homebrew-related lines in your .zprofile are at the very end of the file."

## Installation logs

(base) ➜  ~ pip3 -V
pip 21.0.1 from /Users/usuario/mambaforge/lib/python3.9/site-packages/pip (python 3.9)

<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (Mac): 12.3
- RAM: 32 GB
- Python version: Python 3.10.8
- Installed modules:
brotlipy               0.7.0
certifi                2020.12.5
cffi                   1.14.5
chardet                4.0.0
conda                  4.10.0
conda-package-handling 1.7.2
cryptography           3.4.7
idna                   2.10
mamba                  0.9.1
pip                    21.0.1
pycosat                0.6.3
pycparser              2.20
pyOpenSSL              20.0.1
PySocks                1.7.1
requests               2.25.1
ruamel-yaml-conda      0.15.80
setuptools             49.6.0.post20210108
six                    1.15.0
tqdm                   4.59.0
urllib3                1.26.4
wheel                  0.36.2
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`: ffmpeg version 5.1.2

```
PASTE HERE
```
</details>

**Comment by TanrebCS** [comment] 2022-10-17 21:41
> There is very little information here, you'll need to clarify what exactly it is that does not seem to be working. As of right now, this does not look like a problem with the library.

Sorry, I've upload it wrong. Now it has the info. But also here: "I have an error (detailed by the webpage), but I don't know how to solve it. "A frequent source for installation problems is if pip3 does not point to the correct Python installation on your system. To check this, run pip3 -V: for MacOS Intel, the path should start with /usr/local, and for Apple Silicon with /opt/homebrew. If this is not the case, you either forgot to modify your shell profile (.zprofile) during the installation of Homebrew, or did not reload your shell (e.g., by opening a new terminal) after doing so. It is also possible that some other software (like Pycharm) changed the PATH variable – to fix this, make sure that the Homebrew-related lines in your .zprofile are at the very end of the file."

**Comment by behackl** [comment] 2022-10-25 16:54
Sorry, but there is still very little information here. Do you get an error when calling `manim`? Did the installation fail? If so, we'll need some logs.

Regardless, your Python path suggests that you are using Python from an anaconda-like environment, then the description from the documentation does not necessarily apply.

Feel free to keep commenting here, but I'll close the issue as it is a user problem, and not a problem caused by Manim.

**Closed by behackl** 2022-10-25 16:54 UTC
Labels: installation
